feat(Department): New function for Department Management
eclipse-sw360/sw360 pull request #1502
Opened 2022-04-08 06:57 UTC by tuannn2

Signed-off-by: tuan99123 <tuan2.nguyennhu@toshiba.co.jp>

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change?

Issue: 

### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?
> How should these changes be tested by the reviewer?
> Have you implemented any additional tests?

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

2022-04-14 05:05 UTC, KoukiHama commented
Please check these file which @tienlee made for review
https://github.com/eclipse/sw360/files/8440283/SW360-20220406.-.Demo1439.pptx

2022-04-22 08:01 UTC, JaideepPalit requested changes
Reviewed the PR.
Kindly look into some minor review comments

2022-04-22 08:01 UTC, JaideepPalit commented on frontend/sw360-portlet/src/main/resources/content/Language.properties
> +manually=Manually Activate
Add same in `Language-vi.properties and Language-jp.properties`

2022-04-26 15:59 UTC, KoukiHama commented
How to set up this function.
https://github.com/toshiba/sw360/wiki/Guide_Department_Management.md

2022-04-27 07:07 UTC, tienlee commented
Thank you for your reviewing, @JaideepPalit 
The defects were fixed following your comments, please help me to confirm.

2022-05-25 07:53 UTC, tuannn2 commented on backend/src/src-users/src/main/java/org/eclipse/sw360/users/UserHandler.java
> +        } catch (Exception e) {
thank @JaideepPalit. I changed Exception to IOException!

2022-05-25 07:53 UTC, tuannn2 commented on backend/src/src-users/src/main/java/org/eclipse/sw360/users/UserHandler.java
> +        } catch (Exception e) {
thank @JaideepPalit. I changed Exception to IOException!

2022-05-25 08:54 UTC, tuannn2 commented
Thank you for your reviewing, @JaideepPalit  . I have fixed it according to your review. Please check it!

2022-06-02 10:56 UTC, JaideepPalit approved these changes
Code looks good to me.

2022-07-24 13:01 UTC, KoukiHama commented
@tuannn2 please fix merge conflict

2022-07-25 02:10 UTC, tuannn2 commented
Thank you @KoukiHama. I have resolved the conflict. Please change the label!

2022-12-16 04:54 UTC, tienlee commented
Dear all,

Toshiba's members were updated this PR follow latest code from main branch.
In addition, we also updated the description for "How to test" section. Please check and test this PR.

Thank you very much.

2022-12-19 10:33 UTC, nikkuma7 commented
Kindly make a lar file for Department portlet.so we can directly import the lar file instead doing the manual changes for department page under admin portlet.

2023-01-05 06:53 UTC, nikkuma7 commented
![image](https://user-images.githubusercontent.com/49710817/210718974-ba8b59d2-9d5e-494c-8732-276fecc89841.png)
I'm following as per your given PPT test guide, but Department tab is not showing under the sw360 Administration tab.

2023-01-05 07:27 UTC, tuannn2 commented
Thank you @nikkuma7,

In the latest commit, I created the file lar.
Please import Private Portlet Department in path: frontend/configuration/Private_Pages_7_4_3_18_GA18.lar in source code, instead of having to setup manual portlet.

2023-01-10 06:09 UTC, nikkuma7 commented
Yes, I added a private lar file ( which you mentioned above)
![image](https://user-images.githubusercontent.com/49710817/211474366-71f161e0-a4e5-4a93-9345-1f6b38a73ee7.png)
![image](https://user-images.githubusercontent.com/49710817/211474644-f0b48060-f455-45c1-8307-976e56d3db9a.png)

department page is still not showing.

2023-01-10 11:00 UTC, nikkuma7 commented
yes, I select private and others options like 

1:Import Permissions
2:Mirror with overwriting 
3:use the current user as author
![image](https://user-images.githubusercontent.com/49710817/211533717-7b01839a-1478-4667-a494-436f00ab71c1.png)

could you please let me know your availability on slack so we can discuss there.

2023-02-01 08:55 UTC, KoukiHama commented
> could you please let me know your availability on slack so we can discuss there.

If you are discussing this in a private channel on slack, can you make it public?

2023-02-01 09:10 UTC, tienlee commented
We are discussing on https://sw360chat.slack.com/archives/C04JENDJGUC

I am busy, so I have not solved the issue with @nikkuma7 (added a private lar file but the department page is still not showing) now.

Sorry for this inconvenience.

2023-03-15 04:37 UTC, nikkuma7 commented
![image](https://user-images.githubusercontent.com/49710817/225207490-2f7cff0f-ffb6-4f6a-90d0-5ac0f9d09d49.png)

Now department button is showing in admin tab, but still facing the issue (department page is not loading).
please see the below SS.
![image](https://user-images.githubusercontent.com/49710817/225207880-a616e1d2-cdec-4bcb-939d-723ce804123b.png)

2023-05-03 05:23 UTC, nikkuma7 commented
Test Successful.
![image](https://user-images.githubusercontent.com/49710817/235837933-beffc1d3-9352-4b02-8807-f567cf98c292.png)

2023-05-03 05:24 UTC, nikkuma7 commented
![image](https://user-images.githubusercontent.com/49710817/235838093-48e325ee-35f2-4779-a41e-d81add0ec65f.png)

2023-05-03 05:36 UTC, KoukiHama commented
we will fix conflict soon.
@tuannn2 @tienlee Could you check it?

2023-05-04 03:08 UTC, tuannn2 commented
Thank you @KoukiHama. 
I have resolved the conflict. 
Please change the label !

2023-05-12 03:16 UTC, tienlee commented
JaideepPalit reviewed this PR and tested by nikkuma7. This PR is already to merge.

2023-05-15 05:22 UTC, nikkuma7 commented
@tienlee , Again portlet is not loading.facing issue while loading admin -> department page.

![image](https://github.com/eclipse-sw360/sw360/assets/49710817/d699a40f-72c4-466a-bac8-73109ae4f9fa)

2023-07-11 11:17 UTC, ag4ums approved these changes
working as expected

2023-07-11 11:56 UTC, merged