feat(EditCR): Admin will be able to reassign/edit the Requesting User of CR
eclipse-sw360/sw360 pull request #1896
Opened 2023-04-06 06:31 UTC by afsahsyeda

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

Description:
> Admin will now be able to edit the Requesting User field while editing a clearing request in Requests Portlet

Issue: #1892 

Screenshot:
![image](https://user-images.githubusercontent.com/115608771/230289785-f8fb95da-3506-4051-8b70-07fd8ac3fda9.png)

2023-04-07 10:02 UTC, akapti requested changes
Tested the PR and found issues.

1. The `Requesting User` field is editable even in `Read / View` mode of CR details page.
2. Changing the `Requesting User` in `Edit` mode does not change the requesting user after updating the CR.
3. Changing the `Requesting User` should log as an auto generated comment in comment section of CR.


Screenshot for reference:
![image](https://user-images.githubusercontent.com/50870174/230589527-476ae3ea-ef47-4b5d-8e6b-741c963c59e3.png)

2023-04-10 10:04 UTC, afsahsyeda commented
Hi @akapti ,

I have made the changes and also looked into #1903...Please check.

2023-04-10 11:30 UTC, akapti requested changes

2023-04-10 11:30 UTC, akapti commented on backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
> +            if (!request.equals(currentRequest)) {
remove this condition from here and add it in `updateClearingRequest` function in `ModerationPortletUtils` class.

2023-04-11 08:54 UTC, akapti approved these changes
Code looks good to me.

2023-04-12 06:07 UTC, merged