feat(Project): New configuration make project and releases relationship more flexible
eclipse-sw360/sw360 pull request #1963
Opened 2023-05-16 03:25 UTC by hoangnt2

Add config **enable.flexible.project.release.relationship=true** (/etc/sw360/sw360.properties) to enable the feature.

The following change will work when **enable.flexible.project.release.relationship=true** only.

# **1. Introduction**

This manual aims to introduce the Dependency Network feature.  Refer issue: #1538 
The dependency network feature is a new function to make the dependency management of a project more flexible by allowing the users to customize the dependency graphs of their projects.
To help the reviewers test and review this new feature more quickly and easily, **Toshiba** makes this manual.

# **2. How to test?**
This feature modify the name and the GUI of the “Linked Releases And Projects” to "Dependency Network" tab on the “project edits” page.
Now the “Linked Releases” table could show all dependencies of a project (both direct and transitive ones). Users can modify these dependencies as well.

![dependency_edit](https://github.com/eclipse-sw360/sw360/assets/94659621/e6a57c71-c094-4525-ae95-5cc4aefa495c)

## **2.1. The changes of edit project GUI**
In this section, we will introduce the changes in GUI behaviors. We modified or added 5 sub-functions below: 
 
#### **a. Modify the “Add Releases” button: This button will add a direct dependency (release) in the dependency graph of this project.**

![Add_release_btn](https://github.com/eclipse-sw360/sw360/assets/94659621/59d2dee3-9f18-4035-bd03-769ae2804266)

#### **b. A new icon button to add a dependency (release) to another dependency (release) in the dependency graph. Note that this dependency added is seen as the transitive dependency of this project.**

![add_child](https://github.com/eclipse-sw360/sw360/assets/94659621/16d8f364-c75f-4b48-aab7-f79782b782c2)

#### **c. A new icon button to load the default dependency graph of a dependency (release) by importing the dependency information stored on the component page. Note that this button will load all dependencies (both direct and transitive ones) of the corresponding dependency (release).**

![load_default](https://github.com/eclipse-sw360/sw360/assets/94659621/6f85ea00-c425-4fe6-ab61-9bbb644c2f99)

#### **d. The combo box allows the user to modify the version of a dependency.**

![Select version](https://github.com/eclipse-sw360/sw360/assets/94659621/8ece45a8-849d-4888-9a8a-531c3dd8cabc)

#### **e. The “Check Dependency Network” button will compare and show the different dependency information which is not consistent with the default one stored on the component page by highlighting them. The inconsistency usually happens after users modified the dependency graph or imported an old project.**

![Check_not_match](https://github.com/eclipse-sw360/sw360/assets/94659621/693332e6-ce89-4696-914d-38bfe1e1aff1)

## **2.2. The changes of view detail project GUI**
#### **a. Add a new tab "Dependency Network" tab (hide License Clearing tab).**
It's work same as License Clearing tab but show the data from dependency network

![Dendency_network_view](https://github.com/eclipse-sw360/sw360/assets/94659621/90c70743-32fb-401a-836f-d746b6ae8ee6)

## **2.3 Rest API changes**

Modified Rest APIs

**a. 3.3.13. Get a single project**

Add dependencyNetwork field to response(It will show the dependency network of project (direct and indirect releases)):
```
"dependencyNetwork": [
        {
            "releaseId": "9efc5766cd0c41d4a40547b99f5b91ac",
            "releaseLink": [
                {
                    "releaseId": "3bed97a1c7ac4c32846ef4be985b648c",
                    "releaseLink": [
                        {
                            "releaseId": "6a8250852362462095c57535294039e4",
                            "releaseLink": [],
                            "releaseRelationship": "TO_BE_REPLACED",
                            "mainlineState": "PHASEOUT",
                            "comment": "Test Comment",
                            "createOn": "2023-05-15",
                            "createBy": "admin@sw360.org"
                        }
                    ],
                    "releaseRelationship": "INTERNAL_USE",
                    "mainlineState": "OPEN",
                    "comment": "Test Comment",
                    "createOn": "2023-05-15",
                    "createBy": "admin@sw360.org"
                }
            ],
            "releaseRelationship": "STATICALLY_LINKED",
            "mainlineState": "MAINLINE",
            "comment": "Test Comment",
            "createOn": "2023-05-15",
            "createBy": "admin@sw360.org"
        },
        {
            "releaseId": "f1d860e7576a44798ee3daff57a3a886",
            "releaseLink": [],
            "releaseRelationship": "OPTIONAL",
            "mainlineState": "OPEN",
            "comment": "Test Comment",
            "createOn": "2023-05-15",
            "createBy": "admin@sw360.org"
        }
    ],
```

**b. 3.3.18. Creating a project**

Add the **dependencyNetwork** field to request to create a dependency network for project

- Simple example request (modify releaseIds to the exist releaseIds in sw360):

```
{
    "name": "TestProject1",
    "dependencyNetwork": [
        {
            "releaseId": "9efc5766cd0c41d4a40547b99f5b91ac",
            "releaseLink": [
                {
                    "releaseId": "3bed97a1c7ac4c32846ef4be985b648c",
                    "releaseLink": [
                    ],
                    "releaseRelationship": "INTERNAL_USE",
                    "mainlineState": "OPEN",
                    "comment": "Test Comment",
                    "createOn": "2023-05-15",
                    "createBy": "admin@sw360.org"
                }
            ],
            "releaseRelationship": "STATICALLY_LINKED",
            "mainlineState": "MAINLINE",
            "comment": "Test Comment",
            "createOn": "2023-05-15",
            "createBy": "admin@sw360.org"
        },
        {
            "releaseId": "f1d860e7576a44798ee3daff57a3a886",
            "releaseLink": [],
            "releaseRelationship": "OPTIONAL",
            "mainlineState": "OPEN",
            "comment": "Test Comment",
            "createOn": "2023-05-15",
            "createBy": "admin@sw360.org"
        }
    ]
}
```

**c. 3.3.18. Update a project**
Same request body as create project request

**d. 3.5.18. Delete a release**
Cannot delete release if it is existing in the dependency network of any project

## **2.4 The change in database and migrate data**
- Created new field in project to save the dependency network **releaseRelationNetwork**
- Create **056_migrate_project_dependency_network.py** to migrate data from **releaseIdToUsage** to **releaseRelationNetwork**

# **3. How to review?**
This chapter introduces which file is modified to achieve the corresponding function.

**3.1. Created new field in project to save the dependency network "releaseRelationNetwork"**

## **3.1. Rest API**

**Table 1: RestAPI functions**
| Rest API function  | File Path | Function name|
| ----------- | ----------- |----------- |
| 3.3.13. Get a single project      | rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java|getProject()|
| 3.3.18. Creating a project     | rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java|createProject()|
| 3.3.20. Update a project      | rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java|patchProject()|
| 3.5.18. Delete a release    | rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java|deleteRelease()|

## **3.2. GUI**
** Table 2: UI functions **
| GUI function  | File Path |
| ----------- | ----------- |
| Project edit page (Dependency network tab)     |  - frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp <br>- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/in [...]

2023-05-24 11:06 UTC, KoukiHama commented
@shi9qiu @tienlee 
Please follow Anupam comments.

2023-05-24 11:19 UTC, tienlee commented
Thanks for your comments. I will discuss with Qiu and give feedback you tomorrow.

2023-05-25 10:38 UTC, KoukiHama commented
@shi9qiu any update?

2023-05-25 11:23 UTC, shi9qiu commented
Hi @ag4ums ,

Thank you for your comments.

I have discussed this with Tien-san, please allow me to discuss more about this issue here.

We proposed this function with two modes - ON and OFF. Changes only happen when the user enables this function. If not, everything will be the same as before (at the source code level).

I would like to begin with the second concern - "not seeing an option to view only the direct dependencies separately". It's easy for us to develop a new feature to show the direct dependencies only based on the developed one. For example, hide the transitive dependencies when the user clicks a button. So this would not be a problem.

But we would like to discuss more on the first concern - "it will break all existing clients". Actually, besides the four APIs we modified and the dependency part in GUI, all other APIs and functions can be used as before. To achieve this, we add a new field (releaseRelationNetwork) to store the dependency network (direct dependencies and transitive dependencies) in the project and keep it in sync with the releaseIdToUsage field. The releaseIdToUsage field is not replaced by the new one and still be there. That's also the reason why other functions will not be affected. Besides, We also create a migration script to convert the data from the releaseIdToUsage field to the releaseRelationNetwork field. It will help users to switch between two modes.

I think maybe we use a bad name "Dependency Network" for this new tag. It looks like we drop the "License Clearing" tab and the function in this tab. But actually, the two tabs are almost the same. All functions are kept as before. The only difference is the new tab can show and edit the transitive dependency. So maybe we can still use the name "License Clearing",  and the user may even not notice the change.

I don't know if my reply answers your question and resolves your concerns. Maybe we misunderstand what you mean by "existing clients". But we are so glad to hear more from you and waiting to solve anything you are worrying about.

Thank you!

2023-05-26 11:21 UTC, ag4ums commented
@shi9qiu 

> We proposed this function with two modes - ON and OFF. Changes only happen when the user enables this function. If not, everything will be the same as before (at the source code level).
 `ON/OFF mode is good, so user can choose.`

> I would like to begin with the second concern - "not seeing an option to view only the direct dependencies separately". It's easy for us to develop a new feature to show the direct dependencies only based on the developed one. For example, hide the transitive dependencies when the user clicks a button. So this would not be a problem.
`I think this is an important option to keep UI consistent.` 

> But we would like to discuss more on the first concern - "it will break all existing clients". Actually, besides the four APIs we modified and the dependency part in GUI, all other APIs and functions can be used as before. To achieve this, we add a new field (releaseRelationNetwork) to store the dependency network (direct dependencies and transitive dependencies) in the project and keep it in sync with the releaseIdToUsage field. The releaseIdToUsage field is not replaced by the new one and still be there. That's also the reason why other functions will not be affected. Besides, We also create a migration script to convert the data from the releaseIdToUsage field to the releaseRelationNetwork field. It will help users to switch between two modes.

`let me try to explain it, I tried to used ort analysis to create project and component, yet to use other rest client/s like capycli, and found that the projects and releases are getting created but releases are not linked to projects, as a result they don’t appear in the UI - Dependency Network tab. guessing other clients will also show the same behavior. 
tried to migrate the old project using the script but for migrated projects  'Dependency Network' tab is empty. (guessing migration issue)`

 > I think maybe we use a bad name "Dependency Network" for this new tag. It looks like we drop the "License Clearing" tab and the function in this tab. But actually, the two tabs are almost the same. All functions are kept as before. The only difference is the new tab can show and edit the transitive dependency. So maybe we can still use the name "License Clearing", and the user may even not notice the change.
`on the naming I think 'License clearing' is more meaning full here as this tab primarily helps with the 'license clearing', Depenendy Netwok' naming somehow feels incomplete as this is does not give you a complete network of the dependencies but only dependencies for a project.`  

So, coming back to the first point that enable this option works well, that’s good, so user can choose to enable it but I am afraid once user migrated to this new option to use dependency network functionality will they be able to switchback.... though not sure if the switching back is required, but what worries me.... if this feature is breaking the existing rest-client/s, and if someone do changes at the client side to support 'Dependency Network', that should not break the current flow(as I see the otherway its breaking now).
Let me know your opinion here... how we can resolve this.

2023-05-26 11:59 UTC, shi9qiu commented
Hi @ag4ums ,

Thank you very much for your kind explanation. I understand your concern. 

Please give me some time, I would like to investigate this issue and discuss with @tienlee to consider how to resolve this. I will share our idea with you as soon as we get it. Thanks!

2023-06-05 05:12 UTC, ag4ums commented
@shi9qiu, @tienlee, @hoangnt2 if you take care of the 3rd point about the API then it should be fine.

2023-06-23 11:17 UTC, shi9qiu commented
Hi, @ag4ums 

We have finished a new version and pushed the source code to this PR. This new version is developed based on what we discussed above. Could you help to review it again?

The biggest change of this new version is that we don't change any existing APIs so they can be used as before for the "ON" mode. Instead, We added 3 new APIs related to the dependency network. We also updated the description of this PR to explain this.

If you have any questions or concerns, please feel free to contact us anytime!

2023-06-30 05:12 UTC, KoukiHama commented
we plan to add some test cases for specific options in sw360 properties.

2023-07-21 06:53 UTC, hoangnt2 commented
@GMishx, thanks for your comments. I updated source code following your comments

2023-07-27 07:26 UTC, smrutis1 requested changes
Kindly look into some minor comments

2023-07-27 07:26 UTC, smrutis1 commented on frontend/sw360-portlet/bnd.bnd
> +    com.fasterxml.jackson.core.*,\
Indentation please

2023-07-27 07:26 UTC, smrutis1 commented on frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/ajax/linkedReleaseInNetwork.jsp
> +                    <div style="font-size:1rem; display:flex; width:100%; border: none;">
Kindly try to remove inline css

2023-07-27 08:36 UTC, hoangnt2 commented on frontend/sw360-portlet/bnd.bnd
> +    com.fasterxml.jackson.core.*,\
Fixed

2023-07-27 08:36 UTC, hoangnt2 commented on backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
> +                releaseList = getAccessibleReleases(releaseById.getReleaseIdToRelationship().keySet().stream().collect(Collectors.toSet()), user);
fixed

2023-07-27 08:37 UTC, hoangnt2 commented on libraries/exporters/bnd.bnd
> +    com.fasterxml.jackson.*
fixed

2023-07-27 08:37 UTC, hoangnt2 commented on backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
> +                node.setCreateBy(user.getEmail());
Creator should be the current user

2023-07-27 08:39 UTC, hoangnt2 commented
@smrutis1, I updated source code following your comments, please help me to check them

2023-08-02 11:20 UTC, hoangnt2 commented on frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/ajax/linkedReleaseInNetwork.jsp
> +                    <div style="font-size:1rem; display:flex; width:100%; border: none;">
> Looks like the inline CSS still there.

@smrutis1, fixed

2023-08-03 00:51 UTC, KoukiHama commented
Thank you @smrutis1  for review codes
Now we can merge this PR.

2023-08-03 06:28 UTC, merged