feat(ECC):Added pagination to ECC release list
eclipse-sw360/sw360 pull request #1986
Opened 2023-06-02 08:02 UTC by eldrin30

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
Added pagination code so that release list are loaded 10 at a time on the ECC portlet
> * Which issue is this pull request belonging to and how is it solving it? (*#1985*)

### Suggest Reviewer
> You can suggest reviewers here with an @ag4ums .

### How To Test?
Have a lot of releases (>1000) and then click on ECC portlet

2023-06-07 06:02 UTC, smrutis1 requested changes
Minor change requestes

2023-06-07 06:02 UTC, smrutis1 commented on frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/ecc/EccPortlet.java
> +    public static String nullToEmptyString(Object in) {
Please use the existing method from ` CommonUtils`

2023-06-07 06:04 UTC, smrutis1 requested changes

2023-06-07 06:04 UTC, smrutis1 commented on frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/ecc/EccPortlet.java
> +import com.liferay.portal.kernel.json.JSONArray;
Please re-arrange the imports

2023-06-08 08:12 UTC, nikkuma7 commented
![image](https://github.com/eclipse-sw360/sw360/assets/49710817/167b2e64-480b-476b-aefb-ac031bc9a51c)
Data is not loading due to timeout.

2023-06-09 11:35 UTC, eldrin30 commented
> 
![Capture](https://github.com/eclipse-sw360/sw360/assets/110816493/133223f3-3bce-4d99-85d2-6f1c4ae77e98)
There was some server and indexing issue earlier, but now its working

2023-06-15 07:36 UTC, nikkuma7 commented
Test successful.

2023-06-19 07:25 UTC, smrutis1 approved these changes
Code looks good.

2023-06-21 07:31 UTC, merged