feat(UI/REST): CycloneDX SBOM Importer & Package Portlet
eclipse-sw360/sw360 pull request #1999
Opened 2023-06-12 08:38 UTC by akapti

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
### $`\textcolor{blue}{\text{What is Package Portlet:}}`$ 
- A `Package` portlet is a new feature in SW360.
- `Package` portlet is the third hierarchy level in SW360 after `Components` and `Releases`.
- This is a dedicated portlet in SW360 where `Package` information is stored.
- Users can search for specific `Packages` and link it to `Releases` or `Projects`.
<br>

### $`\textcolor{green}{\text{Task Completed:}}`$
- [x] CycloneDX BOM importer at `Project` homepage & `Project` details page (supports `JSON` & `XML` format).
  - [x] If `VCS` is available in `SBOM` then import by grouping VCS, and create `Component`, `Release` & `Package`.
  - [x] If `VCS` is `not` available in `SBOM` then import without grouping and create only `Package` without linked `Release`.
  - [x] Upload `SBOM` used for import as an attachment in `Project`.
- [x] `Package` portlet homepage UI (listing of all packages).
  - [x] Show Linked `Release` information (like `Release name with version` and `Release Clearing State` ).
  - [x] Edit `Package` and Delete `Package` buttons (Deletion is possible if `Package` is not used in any `Project`).
  - [x] Advanced Search feature.
- [x] Add new `Package` page from `Package` portlet homepage.
- [x] `Package` Edit page.
  - [x] Linking / Unlinking `Release` to / from the `Package`.
  - [x] Delete `Package` (if not used in any `Project`).
- [x] `Package` Details page.
  - [x] `Summary` tab.
  - [x] Using `Projects` Table in `Package` Summary tab.
  - [x] `Change Log` tab.
- [x] `Release` Details page.
  - [x] Linked `Packages` tab.
  - [x] Buttons to `Edit` & `Delete` the `Packages` (Deletion is possible if `Package` is not used in any `Project`).
  - [x] Header level `Search` and `Filter` for `Linked Packages` table.
- [x] `Release` Edit page.
  - [x] Search & Add Linked `Packages` (only Orphan `Packages` can be searched & Linked to a `Release`).
  - [x] Unlink an existing Linked `Packages`.
- [x] Restrict deletion of `Release` if there are Linked `Packages` in it.
- [x] `Project` Details page.
  - [x] Linked `Packages` tab.
  - [x] Show Linked `Release` information in Linked `Packages` tab.
  - [x] Button to Edit the `Packages`.
  - [x] Header level `Search` and `Filter` for `Linked Packages` table.
  - [x] Button to update missing linked `Releases` in `License Clearing` tab.
- [x] `Project` Edit page.
  - [x] Search & Add Linked `Packages`.
  - [x] Unlink an existing Linked `Packages`.
  - [x] Automatically remove linked `Release` when it's only linked `Package` is removed from `Project` (when `Project` is updated).
  - [x] Automatically link a `Release` (if not already linked) when one of it's linked `Packages` is linked to the `Project`  (when `Project` is updated).
- [x] Making `Package` portlet feature configurable. (via `sw360.properties`: `package.portlet.enabled=true` -> default is `false`)
- [x] Feature to upload the `SBOM` import status in `JSON` form as attachment in `Project`.
- [x] Feature to see the detailed view of  `SBOM` import status from an `ImportStatus.json` attachment in `Project`.
- [x] Feature to Copy the information from the SBOM import modal pop-up.
- [x] Feature to `Search` for `Packages` in `Search` portlet.
- [x] REST API:
  - [x] `POST` endpoint to Create a single `Package`.
  - [x] `PATCH` endpoint to Update a `Package`.
  - [x] `DELETE` endpoint to delete a `Package` (Deletion is possible if `Package` is not used in any `Project`).
  - [x] `GET` endpoint to Get a single `Package` with all details.
  - [x] `PATCH` endpoint to link / unlink `Package` to / from `Project`.
  - [x] `POST` endpoint to Import CycloneDX SBOM at `Project` level.
  - [x] `PATCH` endpoint to link / unlink `Package` to / from `Release`.
<br>

### $`\textcolor{orange}{\text{Task In Progress:}}`$ 
- [ ] Restrict `Package` Edit / Update functionality to `Creator` of `Package` or user with minimum role of `Clearing Admin` (user role will be configurable via `sw360.properties` file).
<br>

### $`\textcolor{purple}{\text{Package Managers in Scope:}}`$ 
- Import will [-fail-], if any SBOM contains `Package Manager` other than the list mentioned below.
- Very minimal code changes are needed in `SW360` to support any other SBOM than the one listed below.
- Package Manager type are picked from: https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst
- [x] ALPINE
- [x] ALPM
- [x] APK
- [x] BITBUCKET
- [x] CARGO
- [x] COCOAPODS
- [x] COMPOSER
- [x] CONAN
- [x] CONDA
- [x] CPAN
- [x] CRAN
- [x] DEB
- [x] DOCKER
- [x] DRUPAL
- [x] GEM
- [x] GENERIC
- [x] GITHUB
- [x] GITLAB
- [x] GOLANG
- [x] GRADLE
- [x] HACKAGE
- [x] HEX
- [x] HUGGINGFACE
- [x] MAVEN
- [x] MLFLOW
- [x] NPM
- [x] NUGET
- [x] OCI
- [x] PUB
- [x] PYPI
- [x] RPM
- [x] SWID
- [x] SWIFT
- [x] YARN
- [x] YOCTO
- [ ] ....
<br>

### $`\textcolor{cyan}{\text{Use Case:}}`$ 
- [x] A `Package` cannot be deleted if it's already linked to any `Project`.
- [x] A `Release` cannot be deleted if it contains linked `Packages`.
- [x] Only orphan packages can be linked to a `Release` from `Release` edit page.
- [x] Linking `Package` to `Project` should also link it's `Release` to project (if `Release` is not already linked).
- [x] Un-linking the only `Package` from the `Project` should also unlink it's `Release` from the `Project` (if `Package` is linked to a `Release`).
- [x] Whenever an SBOM is imported from `Project` homepage, a new `Project` (if not already present) will be created with `name` and `version` as that of the `component` present in `metadata` tag of `SBOM` being imported by user.
- [x] Importing SBOM from `Project` details page will not validate the `component` present in `metadata` tag of `SBOM` and import all it's components based on logic mentioned above.
<br>

### $`\textcolor{white}{\text{Link to development branch:}}`$ 
- https://github.com/Siemens-Healthineers/sw360/tree/feat/PackagePortlet-1374-1146
<br>

Issue: #1146 #1374 

### Suggest Reviewer
@smrutis1  

### How To Test?
Will share a detailed description on how to test the PR with all use cases.

### Checklist
Must:
- [X] All related issues are referenced in commit messages and in PR

2023-06-12 09:17 UTC, ag4ums commented
@akapti, thanks for creating this PR , 
I see that two different features are combined here in a single PR, 
my suggestion is to split this into two separate PRs for easy readability and better code review.
maybe one for `Import CycloneDx SBOM` and the other for `Package Protlet`.

2023-06-13 14:24 UTC, akapti commented
Hi All,

- I have marked the PR as `ready for testing`, as the feature is pretty stable and can be tested by anyone.
- Meanwhile I will work on splitting the PR based on CycloneDX BOM importer / exporter and Package portlet.
- If you find any bugs with the feature, Please post a comment in the PR with error logs and screenshots.
- I will update the `How to Test` description soon.

CC: @ag4ums @heliocastro @smrutis1 @afsahsyeda @KoukiHama @arunazhakesan

2023-06-22 07:31 UTC, KoukiHama commented
Hi,  Can I try this PR with [87183da](https://github.com/eclipse-sw360/sw360/commit/87183da36f522206fac8c4ebffb4d36be21cdb94) ?

2023-06-23 21:48 UTC, akapti commented
> Hi, Can I try this PR with [87183da](https://github.com/eclipse-sw360/sw360/commit/87183da36f522206fac8c4ebffb4d36be21cdb94) ?

Just saw your message.
Yes, you can try testing branch with the latest available commit.

2023-06-30 04:08 UTC, KoukiHama commented
I have one  question about the following options
What is expected to be displayed when the following options are enabled?

> component.visibility.restriction.enabled=true

https://github.com/eclipse-sw360/sw360/pull/1357

2023-07-03 09:55 UTC, akapti commented
> I have one question about the following options and this PR for Package Portlet. What is expected to be displayed when the following options are enabled with this PR 1999?
> 
> > component.visibility.restriction.enabled=true
> 
> Ref #1357

aah... I totally missed that part. currently component visibility is not being checked and all components are fetched irrespective of component is visible or not.

2023-07-04 07:23 UTC, KoukiHama commented
https://github.com/eclipse-sw360/sw360/issues/2025
Cyclone DX input/output have the same issue.

2023-07-05 12:15 UTC, KoukiHama commented
> aah... I totally missed that part. currently component visibility is not being checked and all components are fetched irrespective of component is visible or not.

we need to deal with this results, but I will review latest one tomorrow as general test with some options in sw360 properties.

2023-07-06 08:22 UTC, KoukiHama commented
I tried basic functions, it works fine.
But I added a new package page by myself from the admin menu. 

How about making new [Private_Pages_7_4_3_18_GA18.lar](https://github.com/eclipse-sw360/sw360/blob/main/frontend/configuration/Private_Pages_7_4_3_18_GA18.lar) ?

link to release
![image](https://github.com/eclipse-sw360/sw360/assets/39894802/ce46d549-a78b-4f16-a61b-b31dc649de2e)

Male new package
![image](https://github.com/eclipse-sw360/sw360/assets/39894802/ed3699a7-ca5d-4341-8942-ebd961447786)

2023-07-07 08:01 UTC, tienlee requested changes
I have some comments, please take a look.

2023-07-25 02:48 UTC, smrutis1 commented on frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/searchPackages.jsp
> +require(['jquery', 'modules/dialog', 'bridges/datatables', 'utils/keyboard', /* jquery-plugins */ 'jquery-ui' ], function($, dialog, datatables, keyboard) {
May be `/* jquery-plugins */ 'jquery-ui'` can be removed, seems like they are not used.

2023-07-25 02:48 UTC, smrutis1 commented on backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
> +                    // this case is not possible, so return & show appropriate error in UI
It is self-explanatory. May be this comment can be removed.

2023-07-25 10:27 UTC, afsahsyeda commented on backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
> +                    String pkgName = SW360Utils.getVersionedName(pkg.getName(), pkg.getVersion());
This has been taken of while creating the package name 
![image](https://github.com/eclipse-sw360/sw360/assets/115608771/1933aac6-e3b6-48b3-8de5-54e0ab30c591)

2023-07-25 10:33 UTC, afsahsyeda commented on backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
> +                String packageName = StringUtils.EMPTY;
It has been done to make it available for code outside the if/else block.
![image](https://github.com/eclipse-sw360/sw360/assets/115608771/dc9be6dc-36bd-4964-9622-595f97a403ea)

2023-07-26 06:01 UTC, akapti commented
> I have some comments, please take a look.

@tienlee 
incorporated review comments by @afsahsyeda and I have resolved the merge conflicts.

2023-07-26 06:05 UTC, afsahsyeda commented
Hi @smrutis1 ,

Your review comments have been incorporated. Please have a look

2023-07-26 08:18 UTC, KoukiHama approved these changes

2023-07-26 09:49 UTC, merged