feat(rest): API to get vulnerability tracking status
eclipse-sw360/sw360 pull request #2014
Opened 2023-06-23 08:01 UTC by keerthi-bl

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? 
#2013 

> * Did you add or update any new dependencies that are required for your change?
No 

### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?
> How should these changes be tested by the reviewer?

End Point : http://localhost:8080/resource/api/vulnerabilities/trackingstatus/8b3aa2f81a764fb482d6391516d153db

Sample Response : 

{
    "_embedded": {
        "sw360:releaseClearingStatusDatas": [
            {
                "release": {
                    "type": "release",
                    "name": "Component2",
                    "version": "1.0",
                    "componentId": "cb38c33187934c85a3c024414ff2dd2a",
                    "releaseDate": "",
                    "externalIds": {},
                    "additionalData": {},
                    "attachments": [
                        {
                            "filename": "projects-2023-03-02.xlsx",
                            "sha1": "349851d0913535925073ca0d34077bd5bd06c002",
                            "attachmentType": "SOURCE",
                            "createdBy": "admin@sw360.org",
                            "createdTeam": "DEPARTMENT",
                            "createdComment": "",
                            "createdOn": "2023-06-15",
                            "checkedComment": "",
                            "checkStatus": "NOTCHECKED"
                        }
                    ],
                    "createdOn": "2023-01-25",
                    "mainlineState": "OPEN",
                    "clearingState": "NEW_CLEARING",
                    "externalToolProcesses": [],
                    "createdBy": "admin@sw360.org",
                    "contributors": [],
                    "subscribers": [],
                    "roles": {},
                    "mainLicenseIds": [],
                    "otherLicenseIds": [],
                    "vendor": {
                        "type": "vendor",
                        "url": "http://localhost:8999",
                        "shortName": "DV",
                        "fullName": "Demo Vendor"
                    },
                    "languages": [],
                    "operatingSystems": [
                        "Linux"
                    ],
                    "softwarePlatforms": [],
                    "sourceCodeDownloadurl": "",
                    "binaryDownloadurl": "",
                    "externalToolProcessesIterator": [],
                    "cpeId": "",
                    "eccInformation": {
                        "eccStatus": "IN_PROGRESS"
                    }
                },
                "componentType": "SERVICE",
                "projectNames": "Demo Project (11)",
                "mainlineStates": "Open",
                "accessible": true,
                "setMainlineStates": true,
                "setProjectNames": true,
                "setComponentType": true,
                "setRelease": true,
                "setAccessible": true
            }
        ]
    },
    "_links": {
        "curies": [
            {
                "href": "http://localhost:8080/resource/docs/{rel}.html",
                "name": "sw360",
                "templated": true
            }
        ]
    }
}

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

2023-07-07 04:22 UTC, keerthi-bl commented
As per the discussion, the response structure has been changed as follows and committed the changes.

Sample response : 
[
    {
        "releaseid": "e397e509eb2344e28d11898fea168bb0",
        "name": "Component2",
        "projectorigin": "Demo Project (11)",
        "svmtrackingstatus": null,
        "shortstatus": null,
        "type": "SERVICE"
    }
]

2023-08-01 02:12 UTC, hoangnt2 commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/VulnerabilityController.java
> +    @GetMapping(value = VULNERABILITIES_URL + "/trackingstatus" + "/{projectid}")
change

```
trackingstatus -> trackingStatus
projectid -> projectId
```

2023-08-01 02:12 UTC, hoangnt2 commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/VulnerabilityController.java
> +    public void getVulnerabilitiesTrackingStatus(@PathVariable("projectid") String projectId,
use **ResponseEntity** and avoid **HttpServletResponse**

2023-08-01 02:12 UTC, hoangnt2 commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/VulnerabilityController.java
> +            throw new TException(e.why);
Handle exception

2023-08-01 02:23 UTC, hoangnt2 commented
@keerthi-bl, If you can please ignore the unnecessary fields in response

2023-08-01 02:34 UTC, hoangnt2 commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/Sw360VulnerabilityService.java
> +    public List<ReleaseClearingStatusData> getReleaseClearingStatusesWithAccessibility(User user, String projectId)
`getReleaseClearingStatusesWithAccessibility` -> `getReleasesClearingStatusWithAccessibility`

2023-08-01 02:34 UTC, hoangnt2 commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/VulnerabilityController.java
> +                    jobj.addProperty("releaseid", rel.getRelease().getId());
releaseid -> releaseId
projectorigin -> projectOrigin
svmtrackingstatus -> svmTrackingStatus
shortstatus -> shortStatus

2023-08-01 02:34 UTC, hoangnt2 commented on rest/resource-server/src/docs/asciidoc/vulnerabilities.adoc
> +A `GET` request will get vulnerability tracking status.
Make the description more clear

Example: vulnerability tracking status for a project (or something)

2023-08-23 10:26 UTC, keerthi-bl commented
Review comments addressed.

2023-08-23 10:53 UTC, hoangnt2 commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/VulnerabilityController.java
> +        }catch(Exception ex) {
add space after }

2023-08-23 12:13 UTC, keerthi-bl commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/VulnerabilityController.java
> +        }catch(Exception ex) {
Resolved

2023-08-23 12:17 UTC, keerthi-bl commented
Review comment addressed.

2023-09-07 02:49 UTC, hoangnt2 commented
@keerthi-bl, the response body doesn't seem to be in JSON format
![image](https://github.com/eclipse-sw360/sw360/assets/94659621/0beefed3-af79-48c1-91af-f36d64a157cb)

You can try to rewrite the controller like below

```
    @GetMapping(value = VULNERABILITIES_URL + "/trackingStatus" + "/{projectId}")
    public ResponseEntity<List<Map<String, String>>> getVulnerabilitiesTrackingStatus(@PathVariable("projectId") String projectId) throws TException {
        List<Map<String, String>> result = new ArrayList<>();
        try {
            User user = restControllerHelper.getSw360UserFromAuthentication();
            List<ReleaseClearingStatusData> releaseClearingStatusList = vulnerabilityService
                    .getReleasesClearingStatusWithAccessibility(user, projectId);
            releaseClearingStatusList.forEach(rel -> {
                if (rel.getRelease() != null) {
                    Map<String, String> vulnerabilityTrackingStatus = new TreeMap<>();
                    vulnerabilityTrackingStatus.put("releaseId", rel.getRelease().getId());
                    vulnerabilityTrackingStatus.put("name", rel.getRelease().getName());
                    vulnerabilityTrackingStatus.put("projectOrigin",  rel.getProjectNames());
                    vulnerabilityTrackingStatus.put("svmTrackingStatus",
                            null != rel.getRelease().getExternalIds() && !rel.getRelease().getExternalIds().isEmpty()
                                    ? rel.getRelease().getExternalIds().get("svmComponentId")
                                    : "");
                    vulnerabilityTrackingStatus.put("shortStatus",  null != rel.getRelease().getAdditionalData()
                            && !rel.getRelease().getAdditionalData().isEmpty()
                            ? rel.getRelease().getAdditionalData().get("svmShortStatus")
                            : "");
                    vulnerabilityTrackingStatus.put("type",   rel.getComponentType().toString());

                    result.add(vulnerabilityTrackingStatus);
                }
            });
            return ResponseEntity.ok(result);
        } catch (SW360Exception e) {
            throw new TException(e.why);
        } catch(Exception ex) {
            throw new TException(ex.getMessage());
        }
    }
```

2023-09-07 02:58 UTC, hoangnt2 requested changes

2023-09-07 02:58 UTC, hoangnt2 commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/VulnerabilityController.java
> +                            null != rel.getRelease().getExternalIds() && !rel.getRelease().getExternalIds().equals("")
InternalIds  and AddditionalData is a Map so it is always not equal to "". Use isEmpty()

2023-09-12 08:24 UTC, keerthi-bl commented
Review comments addressed.

2023-09-12 09:03 UTC, hoangnt2 requested changes

2023-09-12 09:03 UTC, hoangnt2 commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/VulnerabilityController.java
> +import java.io.IOException;
remove unused import

2023-09-12 09:03 UTC, hoangnt2 commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/VulnerabilityController.java
> +import javax.servlet.http.HttpServletResponse;
remove unused import

2023-09-12 09:03 UTC, hoangnt2 commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/VulnerabilityController.java
> +import com.google.gson.JsonObject;
remove unused import

2023-09-12 11:48 UTC, keerthi-bl commented
Review comments addressed.

2023-09-13 01:53 UTC, hoangnt2 approved these changes
Changes look good

2023-10-04 05:24 UTC, merged