fix(rest): create new endpoint for import OSADL information in admin.
eclipse-sw360/sw360 pull request #2114
Opened 2023-08-31 06:15 UTC by nikkuma7

…tab.

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change?

Issue: #2113 

### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?
1: login sw360 with admin user
2: /resource/api/licenses/import/OSADL

> How should these changes be tested by the reviewer?
> Have you implemented any additional tests?

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

2023-09-05 03:01 UTC, hoangnt2 requested changes

2023-09-05 03:01 UTC, hoangnt2 commented on rest/resource-server/src/docs/asciidoc/licenses.adoc
> +==== Import osdal information
typo osdal -> OSADL (same with other places)

2023-09-05 03:01 UTC, hoangnt2 commented on rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java
> +        mockMvc.perform(post("/api/licenses/" + "/import/OSADL")
`"/api/licenses/" + "/import/OSADL" `can be replaced by `"/api/licenses/import/OSADL"`

2023-09-06 08:18 UTC, nikkuma7 commented on rest/resource-server/src/docs/asciidoc/licenses.adoc
> +==== Import osdal information
done.

2023-09-06 08:39 UTC, hoangnt2 commented
Code look good

2023-10-04 07:27 UTC, keerthi-bl commented
Please add proper response. Now getting just empty message box.

![image](https://github.com/eclipse-sw360/sw360/assets/121924406/e18e2615-643e-4279-b7d0-9b324c0e5cf9)

2023-10-05 09:18 UTC, keerthi-bl commented
Testing completed and working as expected. 

![image](https://github.com/eclipse-sw360/sw360/assets/121924406/53570fa4-ec48-4b3a-996d-2b8e37118e83)

2023-10-18 06:10 UTC, merged