feat(rest) : End point for export vendor spreadsheet
eclipse-sw360/sw360 pull request #2130
Opened 2023-09-29 06:35 UTC by keerthi-bl

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
Issue:  #2124 

> * Did you add or update any new dependencies that are required for your change?
No 

### How To Test?
> How should these changes be tested by the reviewer?
It is a rest end point. It can be tested using Postman client, as follows.

URL : http://localhost:8080/resource/api/vendors/exportVendorDeatails

Click on Send and Download and check the downloaded excel file. Attached sample excel file here.

Sample response : "OK"

![image](https://github.com/eclipse-sw360/sw360/assets/121924406/821bd9d8-95e7-4b50-b2be-772f185e3f5a)

> Have you implemented any additional tests?

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

2023-09-29 08:17 UTC, hoangnt2 requested changes

2023-09-29 08:17 UTC, hoangnt2 commented on backend/src/src-vendors/src/main/java/org/eclipse/sw360/vendors/VendorDatabaseHandler.java
> +        }catch (Exception e) {
add space after }

2023-09-29 08:17 UTC, hoangnt2 commented on rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VendorSpecTest.java
> +        mockMvc.perform(get("/api/vendors/exportVendorDeatails")
typo **exportVendorDeatails** -> **exportVendorDetails**

2023-09-29 08:17 UTC, hoangnt2 commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/VendorController.java
> +    @GetMapping(value = VENDORS_URL + "/exportVendorDeatails")
typo **exportVendorDeatails** -> **exportVendorDetails**

2023-10-03 05:37 UTC, rudra-superrr commented
Testing was successful.

2023-10-03 08:48 UTC, hoangnt2 commented
Code look good

2023-10-04 05:25 UTC, merged