fix(RequestsPortlet): Unable to reopen CR, Open Components to display open releases, clearing progress to show percentage
eclipse-sw360/sw360 pull request #2188
Opened 2023-11-15 08:25 UTC by afsahsyeda

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

**Description**

1. Requesting User and Clearing Expert can reopen a CR.
2. Requesting User can now close the CR.
3. Open Components has been renamed to Open Releases and displays count of Releases in NEW state.
4. Clearing Progress is now presented in percentage.
![image](https://github.com/eclipse-sw360/sw360/assets/115608771/b2ac57c5-01df-44da-ad15-590927a2ced6)

Closes: #2181

2023-11-16 10:28 UTC, akshitjoshii commented
Testing completed, working as expected.
![pr_2182](https://github.com/eclipse-sw360/sw360/assets/142988587/32f5cb55-ebbe-4604-9e1e-aa65e66d4869)
![pr_2182_01](https://github.com/eclipse-sw360/sw360/assets/142988587/0350d6fd-f034-4bdc-abbe-0bb55cf8d4c0)

2023-11-23 02:17 UTC, hoangnt2 requested changes

2023-11-23 02:17 UTC, hoangnt2 commented on frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortletUtils.java
> +                if (requestingUser.equals(user.getEmail())) {
I think in this case, if the requestingUser has role CLEARING_EXPERT and the clearing state is CLOSED, the clearing request state will be set twice time.
Maybe you should replace **if** to **else if**

2023-11-23 05:40 UTC, afsahsyeda commented
Hi @hoangnt2 ,

I have addressed the review comments. Please check.

2023-11-23 08:31 UTC, hoangnt2 reviewed
Change look good to me

2023-11-23 08:31 UTC, hoangnt2 approved these changes

2023-11-24 03:47 UTC, merged