feat(Rest) : Download license clearing report end point.
eclipse-sw360/sw360 pull request #2249
Opened 2023-12-22 08:12 UTC by keerthi-bl

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

closes : #2248 

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)

 #2248 

> * Did you add or update any new dependencies that are required for your change?
No

### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?
> How should these changes be tested by the reviewer?

URL : http://localhost:8080/resource/api/reports?withlinkedreleases=false&module=projects&projectId=bf1570a235414de486eb1043d4b0c0a8&mailrequest=false

Sample respo : 

Excel should get downloaded.

> Have you implemented any additional tests?

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

2024-01-04 06:48 UTC, nikkuma7 commented
Test successful.

![image](https://github.com/eclipse-sw360/sw360/assets/49710817/626a9520-2881-4e6b-8564-0d2039fe40b1)

![image](https://github.com/eclipse-sw360/sw360/assets/49710817/a3201e54-0683-4c7b-971b-f765a0aadb04)

2024-03-01 05:39 UTC, smrutis1 commented on rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
> +    public void should_document_get_project_licenseclearing_report() throws Exception {
Please update the method name as its not the clearing report but the spreadsheet export.

2024-03-01 05:42 UTC, smrutis1 requested changes
One thing I observed that the downloaded spreadsheet name from UI and Rest is different. Please make it consistent. Seems like the project name is not there in the filename.

2024-03-06 05:25 UTC, smrutis1 approved these changes
CLGTM

2024-03-08 08:08 UTC, merged