feat(rest): Create new Api's to track feedback, reverse svm match and schedule svm sync in schedule tab.
eclipse-sw360/sw360 pull request #2269
Opened 2024-01-12 07:41 UTC by nikkuma7

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change?

Issue: #2268 

create new endpoint to schedule svm sync , reverse svm match , track the feedback and cancel services as well.
Note : only admin user can access.

### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?
> How should these changes be tested by the reviewer?
> Have you implemented any additional tests?

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

2024-01-16 08:43 UTC, ag4ums commented
this is remaining work from PR #2243

2024-03-08 06:25 UTC, keerthi-bl commented
Testing this PR

2024-03-08 07:53 UTC, keerthi-bl commented
Test successful.

![test_1](https://github.com/eclipse-sw360/sw360/assets/121924406/5663ac76-81ee-4dd0-8362-254dc2209005)

![test_2](https://github.com/eclipse-sw360/sw360/assets/121924406/b0f8d155-fae1-44fc-a176-54894086b3ac)

![test_3](https://github.com/eclipse-sw360/sw360/assets/121924406/64fdae8d-47cf-47a1-8485-9fdd4e66663b)

![test_4](https://github.com/eclipse-sw360/sw360/assets/121924406/74587aba-123a-4f09-909b-9143d172c718)

![test_5](https://github.com/eclipse-sw360/sw360/assets/121924406/a866214d-360f-49a2-ae92-f91f2cc61d68)

![test_6](https://github.com/eclipse-sw360/sw360/assets/121924406/c2de6390-4f2f-490f-a28d-6c8425bdcba5)

2024-09-06 10:53 UTC, GMishx commented
@nikkuma7 please rebase with latest main

2024-10-18 09:19 UTC, GMishx requested changes

2024-10-18 09:19 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/schedule/ScheduleAdminController.java
> +        HttpStatus status = HttpStatus.OK;
Please consider using `202 ACCEPTED` instead of `200 OK` as no immediate action is taken for all endpoints.

2024-10-18 09:19 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/schedule/Sw360ScheduleService.java
> +                throw new RuntimeException("User is not admin");
Please use appropriate exceptions like `AccessDeniedException` instead.

2024-10-18 09:19 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/schedule/Sw360ScheduleService.java
> +        }
This exception handling makes no sense as `TException` is captured and thrown.

I would rather recommend logging the exception with `log.error("Some appropriate message here", e)` and re-throw the captured exception `e`.

2024-10-21 10:29 UTC, GMishx approved these changes
Changes looks good.

2024-11-27 08:14 UTC, GMishx approved these changes

2024-11-27 08:15 UTC, merged