feat(rest): Create new endpoint to download component template in csv format.
eclipse-sw360/sw360 pull request #2278
Opened 2024-01-19 07:55 UTC by nikkuma7

… format.

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change?

Issue: #2277 

### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?
> How should these changes be tested by the reviewer?
> Have you implemented any additional tests?

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

2024-04-23 07:41 UTC, rudra-superrr commented
Docs are broken.

![image](https://github.com/eclipse-sw360/sw360/assets/58290634/e2495925-bf93-4ab7-ac0a-578d0a37e598)

2024-04-23 08:03 UTC, rudra-superrr commented
Endpoints working fine
![image](https://github.com/eclipse-sw360/sw360/assets/58290634/48120ff9-2edf-4539-a704-59516ab4fb94)

2024-04-24 05:41 UTC, rudra-superrr commented
Endpoint for download component csv and download license archive are missing under export section.
![image](https://github.com/eclipse-sw360/sw360/assets/58290634/e49e61b4-e666-418b-8e87-84e98702ebc8)

2024-05-16 09:44 UTC, nikkuma7 commented
> Endpoint for download component csv and download license archive are missing under export section. ![image](https://private-user-images.githubusercontent.com/58290634/325093478-e49e61b4-e666-418b-8e87-84e98702ebc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NDcyNjgsIm5iZiI6MTcxNTg0Njk2OCwicGF0aCI6Ii81ODI5MDYzNC8zMjUwOTM0NzgtZTQ5ZTYxYjQtZTY2Ni00MThiLThlODctODRlOTg3MDJlYmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDA4MDkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExZDg1ZGU1MGE2NjAwODAyM2E0NzFkNjlhODE4ODliZTUwODQzZDM0MDMyMmY3YmY4NDIxZjQ5ZDlhMzA4NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2ePwDy23vGOGuqMfOMjnb6YaiGQrw39qlhOxLKs6czI)

@rudra-superrr , Already endpoint is there for Download license archive(under Admin tab -> license).

2024-05-17 06:08 UTC, rudra-superrr commented
Testing was successful and please look into Download Component CSV export button.

2024-08-30 06:41 UTC, keerthi-bl reviewed
@nikkuma7 Please do update the review changes

2024-08-30 06:41 UTC, keerthi-bl commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/Sw360ImportExportService.java
> +            throw new RuntimeException("Unable to download CSV component template. User is not admin");
throw a dedicated exception instead of using a generic one.

2024-08-30 06:41 UTC, keerthi-bl commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/Sw360ImportExportService.java
> +            throw new RuntimeException("Unable to download CSV attachment template. User is not admin");
throw a dedicated exception instead of using a generic one

2024-08-30 06:41 UTC, keerthi-bl commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/Sw360ImportExportService.java
> +            throw new RuntimeException("Unable to download CSV attachment information. User is not admin");
throw a dedicated exception instead of using a generic one

2024-08-30 06:41 UTC, keerthi-bl commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/Sw360ImportExportService.java
> +        String fileConstant="ComponentsReleasesVendorsSample.csv";
"**fileConstant**" : Since its used only once, no need to create a separate String parameter.

2024-08-30 06:41 UTC, keerthi-bl commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/Sw360ImportExportService.java
> +        response.setHeader("Content-Disposition", String.format("Components; filename=\"%s\"", filename));
**"Content-Disposition"**  Create a constant variable and replace in all the places.

2024-08-30 06:41 UTC, keerthi-bl commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/Sw360ImportExportService.java
> +            throw new RuntimeException("Unable to download CSV release link. User is not admin");
Throw dedicated exception instead of using a generic one.

2024-08-30 06:41 UTC, keerthi-bl commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/Sw360ImportExportService.java
> +            throws TException, IOException {
Remove the declaration of thrown exception '**TException**', as it cannot be thrown from method's body.

2024-08-30 06:41 UTC, keerthi-bl commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/Sw360ImportExportService.java
> +    public void getDownloadAttachmentInfo(User sw360User, HttpServletResponse response) throws TException, IOException {
Remove unused throw exceptions.

2024-08-30 06:41 UTC, keerthi-bl commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/Sw360ImportExportService.java
> +        ComponentService.Iface componentClient = new ThriftClients().makeComponentClient();
Immediately return this expression instead of assigning it to the temporary variable "**componentClient**".

2024-08-30 06:41 UTC, keerthi-bl commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/Sw360ImportExportService.java
> +            return null;
Instead of null return, maybe its better to return emptyCollections.

2024-08-30 06:41 UTC, keerthi-bl commented on rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ImportExportSpecTest.java
Please check the documentation once with latest main branch.

2024-09-02 07:27 UTC, nikkuma7 commented on rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ImportExportSpecTest.java
@keerthi-bl , comment Addressed.

2024-10-17 08:36 UTC, GMishx requested changes
Minor changes nneded.

2024-10-17 08:36 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/Sw360ImportExportService.java
> +            throw new HttpMessageNotReadableException("User is not admin");
Please use `org.springframework.security.access.AccessDeniedException` exception instead.

2024-10-17 08:36 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/Sw360ImportExportService.java
> +            throw new HttpMessageNotReadableException("User is not admin");
Please use `org.springframework.security.access.AccessDeniedException` exception instead.

2024-10-17 08:36 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/Sw360ImportExportService.java
> +import org.eclipse.sw360.datahandler.thrift.SW360Exception;
Please organize unused imports.

2024-10-17 08:36 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/Sw360ImportExportService.java
> +            throw new HttpMessageNotReadableException("User is not admin");
Please use `org.springframework.security.access.AccessDeniedException` exception instead.

2024-10-17 08:36 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/Sw360ImportExportService.java
> +            throw new HttpMessageNotReadableException("User is not admin");
Please use `org.springframework.security.access.AccessDeniedException` exception instead.

2024-10-17 08:36 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/Sw360ImportExportService.java
> +        String filename = String.format("ComponentsReleasesVendorsSample.csv", SW360Utils.getCreatedOn());
Placeholder for `SW360Utils.getCreatedOn()` is missing in the format string.

2024-10-17 08:36 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/Sw360ImportExportService.java
> +        String filename = String.format("AttachmentInfo_Sample.csv", SW360Utils.getCreatedOn());
Placeholder is missing in the format string.

2024-10-17 08:36 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/Sw360ImportExportService.java
> +        String filename = String.format("AttachmentInfo.csv", SW360Utils.getCreatedOn());
Placeholder is missing in the format string.

2024-10-17 08:36 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/Sw360ImportExportService.java
> +        String filename = String.format("ReleaseLinkInfo_Sample.csv", SW360Utils.getCreatedOn());
Placeholder is missing in the format string.

2024-10-17 08:36 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/Sw360ImportExportService.java
> +        String filename = String.format("ReleaseLinkInfo.csv", SW360Utils.getCreatedOn());
Placeholder is missing in the format string.

2024-10-17 08:36 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/Sw360ImportExportService.java
> +        String filename = String.format("ComponentsReleasesVendors.csv", SW360Utils.getCreatedOn());
Placeholder is missing in the format string.

2024-10-18 06:50 UTC, nikkuma7 commented
Addressed comment.

2024-10-18 08:07 UTC, nikkuma7 commented
Addressed comment.

2024-10-18 09:14 UTC, GMishx approved these changes
Changes looks good.

2024-10-18 09:15 UTC, merged