feat(rest): create new enpoint to upload component csv file.
eclipse-sw360/sw360 pull request #2308
Opened 2024-02-12 07:15 UTC by nikkuma7

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change?

Issue: #2307 

### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?
> How should these changes be tested by the reviewer?
> Have you implemented any additional tests?

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

2024-09-06 10:53 UTC, GMishx commented
@nikkuma7 please rebase with latest main

2024-09-10 05:20 UTC, nikkuma7 commented
Done. Rebase with latest main.

2024-10-17 08:41 UTC, GMishx requested changes
Minor change needed.

2024-10-17 08:41 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/Sw360ImportExportService.java
> +            throw new RuntimeException("Unable to upload component csv file. User is not admin");
Please use `org.springframework.security.access.AccessDeniedException` exception instead.

2024-10-17 08:41 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/Sw360ImportExportService.java
> +            throw new RuntimeException("Unable to upload component csv file. User is not admin");
Please use `org.springframework.security.access.AccessDeniedException` exception instead.

2024-10-18 06:08 UTC, nikkuma7 commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/Sw360ImportExportService.java
> +            throw new RuntimeException("Unable to upload component csv file. User is not admin");
done.

2024-10-21 12:40 UTC, GMishx submitted a review, later dismissed
Changes looks good. Please rebase once @nikkuma7

2024-10-21 12:41 UTC, GMishx commented
@rudra-superrr please help with testing this PR.

2024-10-28 06:32 UTC, rudra-superrr commented
Rest docs are broken.
![image](https://github.com/user-attachments/assets/ac8b73dc-47ab-4bc9-8b61-46e2ff056719)

2024-11-03 09:07 UTC, nikkuma7 commented
> Rest docs are broken. ![image](https://private-user-images.githubusercontent.com/58290634/380602303-ac8b73dc-47ab-4bc9-8b61-46e2ff056719.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MjEzNjgsIm5iZiI6MTczMDYyMTA2OCwicGF0aCI6Ii81ODI5MDYzNC8zODA2MDIzMDMtYWM4YjczZGMtNDdhYi00YmM5LThiNjEtNDZlMmZmMDU2NzE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDA4MDQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5NmVkYTA5OGExMzQ5M2I0NWFjNjAzMzgwMTAxZjBiNjRjOTE5YWViYTQ1OThjZmJmY2NiOGVlMjg5NTk5NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4xmMjfcuvuE9K5PFALoCNnQC7fEAk4TeIjeyRS-09yc)

done.

2024-11-07 06:16 UTC, rudra-superrr commented
Docs are still broken.

2024-12-04 06:54 UTC, GMishx requested changes

2024-12-04 06:54 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/ImportExportController.java
> +            "ImportExport" }, parameters = { @Parameter(name = "Accept", in = ParameterIn.HEADER, required = true), })
Please revert the unnecessary changes.

2024-12-04 06:54 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/ImportExportController.java
> +            "ImportExport" }, parameters = { @Parameter(name = "Accept", in = ParameterIn.HEADER, required = true), })
Please revert the unnecessary changes.

2024-12-04 06:54 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/ImportExportController.java
> +            "ImportExport" }, parameters = { @Parameter(name = "Accept", in = ParameterIn.HEADER, required = true), })
Please revert the unnecessary changes.

2024-12-04 06:54 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/ImportExportController.java
> +            "ImportExport" }, parameters = { @Parameter(name = "Accept", in = ParameterIn.HEADER, required = true), })
Please revert the unnecessary changes.

2024-12-04 06:54 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/ImportExportController.java
> +            "ImportExport" }, parameters = { @Parameter(name = "Accept", in = ParameterIn.HEADER, required = true), })
Please revert the unnecessary changes.

2024-12-04 06:54 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/ImportExportController.java
> +            "ImportExport" }, parameters = { @Parameter(name = "Accept", in = ParameterIn.HEADER, required = true), })
Please revert the unnecessary changes.

2024-12-04 06:54 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/ImportExportController.java
> +            "Component" })
The tag should be `ImportExport` as with other endpoints.

2024-12-04 06:54 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/ImportExportController.java
> +            "Component" })
Also, please document the header needed as done in `downloadComponent()` for the `Content-Type` header (put in `consumes`).

2024-12-04 06:54 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/ImportExportController.java
> +    @Operation(summary = "release link file.", description = "release link file.", tags = { "Release" })
The tag should be `ImportExport` as with other endpoints.

```suggestion
    @Operation(summary = "Import releases.", description = "Upload CSV with release link to import.", tags = { "ImportExport" })
```

2024-12-04 06:54 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/ImportExportController.java
> +    @Operation(summary = "release link file.", description = "release link file.", tags = { "Release" })
Also, please document the header needed as done in `downloadComponent()` for the `Content-Type` header (put in `consumes`).

2024-12-04 06:54 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/Sw360ImportExportService.java
> +    }
The functions are already defined in `libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftClients.java`. Please use them instead.

2025-01-06 08:27 UTC, nikkuma7 commented
@GMishx Comment Addressed.

2025-01-06 09:17 UTC, GMishx approved these changes
Changes looks good.

2025-01-06 09:38 UTC, merged