feat (Rest): Create endpoint to search User Byname using lucene search.
eclipse-sw360/sw360 pull request #2335
Opened 2024-03-01 08:22 UTC by nikkuma7

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change?

Issue: Closes : #2334 

### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?
http://localhost:8080/resource/api/users/name?page=true&page_entries=Test&sort=admin1&givenname=test&luceneSearch=true&email=admin1

![image](https://github.com/eclipse-sw360/sw360/assets/49710817/d88c2788-a740-4c8f-b201-6adfdfc18835)

> How should these changes be tested by the reviewer?
> Have you implemented any additional tests?

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

2024-03-04 06:58 UTC, smrutis1 requested changes
Please refer `/api/projects?name=xxx` and do the changes accordingly.

Reference of Project endpoint by name:
https://github.com/eclipse-sw360/sw360/blob/737a1320bd3a611c93a48e89ad3b6eea61fca3dd/rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java#L227

2024-03-04 06:58 UTC, smrutis1 commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/UserController.java
> +    public ResponseEntity<CollectionModel<EntityModel<User>>> getUsersByName(
Instead of creating a new endpoint. Kindly add a parameter in the existing get user endpoint viz. `/api/users?name=xxx`.

2024-03-04 06:58 UTC, smrutis1 commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/UserController.java
> +        List<EntityModel<User>> userResources = new ArrayList<>();
Seems like if name is not present then it will return all the users instead it should query(not lucene) the database for the user.

2024-03-06 04:17 UTC, nikkuma7 commented
> Please refer `/api/projects?name=xxx` and do the changes accordingly.
> 
> Reference of Project endpoint by name:
> 
> https://github.com/eclipse-sw360/sw360/blob/737a1320bd3a611c93a48e89ad3b6eea61fca3dd/rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java#L227

Review comment addressed.

2024-03-20 05:56 UTC, keerthi-bl commented
Testing this PR

2024-03-21 05:34 UTC, keerthi-bl commented
Test Successful.

![image](https://github.com/eclipse-sw360/sw360/assets/121924406/eb65308d-8572-49cc-acd8-8f1d19b19fb7)

2024-03-21 07:31 UTC, smrutis1 approved these changes
CLGTM

2024-03-22 08:57 UTC, merged