feat(CR): Update clearing request state from AWAITING RESPONSE to PENDING INPUT
eclipse-sw360/sw360 pull request #2375
Opened 2024-03-21 11:24 UTC by akshitjoshii

Issue:Closes #2374 
Changes the Clearing status from "Awaiting Response" to "Pending Input" as it requires input from the CR requester and more intuitive for the user.

2024-03-22 07:07 UTC, afsahsyeda requested changes

2024-03-22 07:07 UTC, afsahsyeda commented on frontend/sw360-portlet/src/main/resources/content/Language.properties
> +pending.input=Pending Input
This should come after p in alphabetical order

2024-03-22 07:07 UTC, afsahsyeda commented on frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
> +pending.input=Pending Input
maintain alphabetical order

2024-03-22 07:07 UTC, afsahsyeda commented on frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
> +pending.input=Pending Input
maintain alphabetical order

2024-03-22 07:07 UTC, afsahsyeda commented on frontend/sw360-portlet/src/main/resources/content/Language_zh.properties
> +pending.input=Pending Input
maintain alphabetical order

2024-03-22 08:41 UTC, sameed20 commented
Testing this PR.

2024-03-25 08:39 UTC, akshitjoshii commented
Addressed review comments.

2024-03-25 08:48 UTC, heliocastro reviewed
Is this not a HUGE breaking change ?
One thing is change the messages, other is change the id of a database enum.
Do we have automated migration scripts ?

@KoukiHama How is this related to Toshiba ?

2024-03-25 09:06 UTC, afsahsyeda commented
> Is this not a HUGE breaking change ? One thing is change the messages, other is change the id of a database enum. Do we have automated migration scripts ?
> 
> @KoukiHama How is this related to Toshiba ?

Hi @heliocastro , the value of the enum remains the same on the backend. Only the term has been updated to "PENDING_INPUT" to align with its corresponding title that states "Clearing Team is waiting for input/action from the Requesting User".

2024-03-26 06:52 UTC, sameed20 commented
Hi @akshitjoshii After these changes the CR's which are created before introducing this feature are not loading.

2024-04-01 06:31 UTC, akapti commented
> Hi @akshitjoshii After these changes the CR's which are created before introducing this feature are not loading.

For old CR's to load, One should write database migration script, like @heliocastro suggested.
What's the requirement @akshitjoshii ?
Is it to replace the existing entry `Awaiting response` with new entry `Pending Input`? or just to add new entry `Pending Input`?

If it's replacing then you need to add database script for migrating old CR's in `Awaiting response` state.

2024-04-01 10:16 UTC, akshitjoshii commented
Hi @akapti as per the new requirement a new field called "PENDING INPUT" is to be added keeping the existing entry "AWAITING RESPONSE" as it is. Then a migration script won't be needed.

2024-04-15 13:53 UTC, akshitjoshii commented
As per suggestion, a new state PENDING INPUT has been added keeping the existing state AWAITING RESPONSE as it is.

2024-04-25 04:55 UTC, afsahsyeda requested changes

2024-04-25 04:55 UTC, afsahsyeda commented on frontend/sw360-portlet/src/main/resources/content/Language.properties
> +ClearingRequestState=New: CR is pending to be Accepted by the Clearing Team.&#10A sanity check for the artifacts required for Clearing will be done prior to Accepting a CR. &#10Pending Input: Inputs
Pending Input: 
The input needed for clearing is incomplete. The clearing team cannot proceed to the next stage of processing the CR until the project provides the missing input.
Sanity Check:
The Clearing team is conducting a sanity check on the inputs provided by the project team. At this stage, they verify the availability of the source code for all linked releases

Please change the titles accordingly.

2024-04-25 04:55 UTC, afsahsyeda commented on frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
> +ClearingRequestState-SANITY_CHECK = A sanity check for the artifacts required for Clearing will be done prior to Accepting a CR
ClearingRequestState-SANITY_CHECK = Prior to accepting a CR, a sanity check for the artifacts required for Clearing will be performed.

2024-04-25 05:44 UTC, sameed20 commented
Test Successful.
![pr_testing](https://github.com/eclipse-sw360/sw360/assets/141239852/8f03f627-6987-4021-897d-4feac47247c4)
![pr_testing_3](https://github.com/eclipse-sw360/sw360/assets/141239852/bdf62d86-9b21-445f-a1b5-09db9469b31e)

2024-04-29 09:43 UTC, sameed20 commented
Test Successful.
![new_testing_1](https://github.com/eclipse-sw360/sw360/assets/141239852/8c31f8af-8b94-44b5-abe4-397d0238e779)
![new_testing_2](https://github.com/eclipse-sw360/sw360/assets/141239852/bf290078-5526-4acb-953a-feae9acf6420)
![new_testing_3](https://github.com/eclipse-sw360/sw360/assets/141239852/41cafeb4-d93e-40b9-9400-c47d86f46543)

2024-05-06 13:30 UTC, afsahsyeda commented
Code looks good to me.

2024-05-06 13:30 UTC, afsahsyeda approved these changes

2024-05-08 09:51 UTC, merged