fix for the (https://github.com/eclipse-sw360/sw360/issues/2310) source code upload for the release
eclipse-sw360/sw360 pull request #2378
Opened 2024-03-22 07:50 UTC by FarooqAftab

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change?

Issue: 
https://github.com/eclipse-sw360/sw360/issues/2310

### Suggest Reviewer
> @afsahsyeda 
### How To Test?
> How should these changes be tested by the reviewer?
> Have you implemented any additional tests?

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

2024-03-23 14:41 UTC, afsahsyeda commented
Hi @FarooqAftab , please amend the commit message to follow the conventional  format. Suggestion- fix(SRCUploadService): Source upload should work for release versions having alphanumeric characters.

2024-03-25 14:19 UTC, afsahsyeda requested changes

2024-03-25 14:19 UTC, afsahsyeda commented on backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
> + /*
Remove the extra space

2024-03-26 10:54 UTC, FarooqAftab commented on backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
> +        Pattern pattern = Pattern.compile(".*/([^/]+)/archive/refs/tags/(?:v)?(.*).zip$");
@afsahsyeda necessary changes have been done. Request to review it once.

2024-03-27 09:23 UTC, afsahsyeda commented on backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
> + /*
Please look into this.

2024-03-27 09:24 UTC, afsahsyeda commented on backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
> +        Pattern pattern = Pattern.compile(".*/([^/]+)/archive/refs/tags/(?:v)?(.*).zip$");
@FarooqAftab the changes look good. Please address the comment at the top so I can approve this.

2024-03-27 10:05 UTC, afsahsyeda commented on backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
> +        Pattern pattern = Pattern.compile(".*/([^/]+)/archive/refs/tags/(?:v)?(.*).zip$");
@FarooqAftab https://www.eclipse.org/legal/ECA.php You can click on "Sign" under "ECA" tab. You need an account in Eclipse first.

2024-03-29 08:33 UTC, afsahsyeda commented
@FarooqAftab kindly address the above comments.

2024-04-03 04:58 UTC, FarooqAftab commented on backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
> +        Pattern pattern = Pattern.compile(".*/([^/]+)/archive/refs/tags/(?:v)?(.*).zip$");
@afsahsyeda ECA has been signed. Please proceed with the ticket.

2024-04-03 09:30 UTC, FarooqAftab commented on backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
> +        Pattern pattern = Pattern.compile(".*/([^/]+)/archive/refs/tags/(?:v)?(.*).zip$");
@afsahsyeda  no extra spaces are shown , can you please confirm it once again
![image](https://github.com/eclipse-sw360/sw360/assets/161705457/f0a7abba-ba81-480c-8516-6c16fd492ea0)

2024-04-03 10:27 UTC, FarooqAftab commented on backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
> +        Pattern pattern = Pattern.compile(".*/([^/]+)/archive/refs/tags/(?:v)?(.*).zip$");
@afsahsyeda Extra tab space have been removed, request to review it once.

2024-04-03 10:28 UTC, afsahsyeda commented
Code looks good to me.

2024-04-03 10:29 UTC, sameed20 commented
Testing this PR

2024-04-03 10:31 UTC, afsahsyeda approved these changes

2024-04-04 07:49 UTC, sameed20 commented
Test Successful
![test_src_upload_1](https://github.com/eclipse-sw360/sw360/assets/141239852/d4acd8c0-449f-4385-a777-d5418812c3b1)
![test_src_upload_2](https://github.com/eclipse-sw360/sw360/assets/141239852/6da601f6-f587-4bd3-a145-36507c6573eb)

2024-04-08 09:20 UTC, afsahsyeda commented
![image](https://github.com/eclipse-sw360/sw360/assets/115608771/f4a0b389-ac07-4263-bdf5-bf8f085f3639)
@FarooqAftab please make the suggested change. This is important because the hardcoded logic works only for github.com domain VCS.

2024-04-10 05:36 UTC, FarooqAftab commented
> ![image](https://private-user-images.githubusercontent.com/115608771/320425056-f4a0b389-ac07-4263-bdf5-bf8f085f3639.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3Mjc1NTMsIm5iZiI6MTcxMjcyNzI1MywicGF0aCI6Ii8xMTU2MDg3NzEvMzIwNDI1MDU2LWY0YTBiMzg5LWFjMDctNDI2My1iZGY1LWJmOGYwODVmMzYzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQwNTM0MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MjU3Y2U3NTVhYzQzOThiZjU0MzRkMTU0YzA0ZWQ2MzMyNzQ1OGYwYTYxYTk2ZGIxOTVjMDRiYmNmYWFhYWRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Xst_yRA7nVyndSiCuxNAD0yI99q5But1eMphFRNccME) @FarooqAftab please make the suggested change. This is important because the hardcoded logic works only for github.com domain VCS. This is line 3084 in ComponentDatabaseHandler.java.

@afsahsyeda  requested changes done, request to review it once

2024-04-15 05:56 UTC, FarooqAftab commented
> Hi @FarooqAftab I came across a use-case when **github.com** part has irregular casing in it this PR is failing for e.g. when a comp has such kind of VCS (mentioned below) present the SRC code is not getting download even for the valid releases and as soon as I'm correcting the casing of **github.com** part the feature is working as expected. Please look into the same.
> 
> https://Github.com/ant-design/ant-design-icons and https://github.Com/ant-design/ant-design-icons

@sameed20 The issue is fixed , request to test it once again

2024-04-15 10:28 UTC, sameed20 commented
Test Successful
![aic_test](https://github.com/eclipse-sw360/sw360/assets/141239852/5d491e85-89a2-426b-b529-9824accf612e)

2024-04-15 10:33 UTC, afsahsyeda requested changes

2024-04-15 10:33 UTC, afsahsyeda commented on backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
> +            String VCS = c.getVcs().toLowerCase();
@FarooqAftab you need to make the change on line 3070. Converting the entire vcs to lower case and then processing it might cause unwanted issues.

2024-04-15 12:38 UTC, afsahsyeda approved these changes

2024-04-15 12:39 UTC, afsahsyeda commented
Code looks good to me.

2024-04-16 06:25 UTC, FarooqAftab commented
@afsahsyeda can we have this PR merged in the main branch.

2024-04-17 12:09 UTC, merged