fix(Rest): Adding vcs field in component update api
eclipse-sw360/sw360 pull request #2383
Opened 2024-03-27 06:01 UTC by FarooqAftab

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Resolves https://github.com/eclipse-sw360/sw360/issues/2376 
> * Did you add or update any new dependencies that are required for your change?

Issue: https://github.com/eclipse-sw360/sw360/issues/2376

### Suggest Reviewer
> @ag4ums 

### How To Test?
> Test by passing vcs field in the request body of the patch api to update component  using http://localhost:8080/resource/api/components/{id}
> Have you implemented any additional tests?

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

2024-04-01 11:44 UTC, akshitjoshii commented
Testing this PR

2024-04-02 08:28 UTC, akshitjoshii commented
Testing done. Currently user can put any and every string in the VCS field as their is no validation being performed. Maybe a check can be added.
![image](https://github.com/eclipse-sw360/sw360/assets/142988587/6355022e-1a72-4431-a5dd-364d255a28dc)

2024-04-02 08:40 UTC, afsahsyeda commented
@FarooqAftab you can implement a regex check for VCS URL before updating the component either in the service or controller class.

2024-04-05 05:23 UTC, FarooqAftab commented
> @FarooqAftab you can implement a regex check for VCS URL before updating the component either in the service or controller class.

@akshitjoshii @afsahsyeda URL Validation has been implemented , request to please test and review it once.

2024-04-16 06:32 UTC, rajaraajeshwari commented
Hi @afsahsyeda 
Could you please let us know when this PR will be merged.

2024-10-16 09:55 UTC, afsahsyeda commented
@FarooqAftab Please resolve the conflicts.

2024-11-05 05:15 UTC, GMishx commented
@afsahsyeda the conflicts have been resolved. Can you please test/review this PR?

2024-11-05 07:36 UTC, akshitjoshii commented
PR still has liferay folder and not rebased with latest main causing build to fail.

2024-11-05 09:57 UTC, GMishx requested changes
@FarooqAftab , please rebase the branch for testing and reviewing.

2024-11-18 10:34 UTC, afsahsyeda commented
@FarooqAftab Kindly resolve the merge conflicts

2024-12-23 08:42 UTC, GMishx requested changes

2024-12-23 08:42 UTC, GMishx commented on libraries/datahandler/src/main/thrift/components.thrift
> +    56: optional string vcs,
Please add the appropriate json ignore for this new field (like `setVcs`)

https://github.com/eclipse-sw360/sw360/blob/dfc187d9f609fa6644b8d5e38752c31236288d86/rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java#L826

2026-04-27 18:15 UTC, GMishx commented
Done in #3635

2026-04-27 18:15 UTC, closed without merging