fix(rest): Added a commit message while create a moderation request.
eclipse-sw360/sw360 pull request #2405
Opened 2024-04-13 06:59 UTC by nikkuma7

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change?

Issue: Closes : #2404 

### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?
> How should these changes be tested by the reviewer?
> Have you implemented any additional tests?

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

2024-10-21 10:39 UTC, GMishx commented
(from discussion) The new front-end should be aware that current action will result in a Moderation Request and should capture comment from user before submitting. This is the current behavior of existing UI with Liferay.

2024-12-04 10:37 UTC, GMishx requested changes
Lot of irrelevant changes make PR hard to review. Please revert them.

2024-12-04 10:37 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> +            .map(MainlineState::name).collect(Collectors.toList());
Please revert irrelevant changes.

2024-12-09 09:09 UTC, nikkuma7 commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> +                .put(Project._Fields.SECURITY_RESPONSIBLES.toString(), securityResponsible).build();
I rebase the code with latest main.

2024-12-10 07:29 UTC, GMishx requested changes
Response status needs to be changed for bad request.

2024-12-10 07:29 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
> +            @RequestParam(value = "comment", required = false) String comment
Documentation still missing.

2024-12-10 07:29 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
> +            @RequestParam(value = "comment", required = false) String comment
Documentation still missing.

2024-12-10 07:29 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
> +            @RequestParam(value = "comment", required = false) String comment
Documentation still missing.

2024-12-10 07:29 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
> +                return new ResponseEntity(RESPONSE_BODY_FOR_MODERATION_REQUEST, HttpStatus.ACCEPTED);
In case of missing request parameter, shouldn't the response status be `BAD_REQUEST`?

2024-12-10 07:29 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
> +            return new ResponseEntity(RESPONSE_BODY_FOR_MODERATION_REQUEST_WITH_COMMIT, HttpStatus.FORBIDDEN);
In case of missing request parameter, shouldn't the response status be `BAD_REQUEST`?

2024-12-10 07:29 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
> +            return new ResponseEntity(RESPONSE_BODY_FOR_MODERATION_REQUEST_WITH_COMMIT, HttpStatus.ACCEPTED);
In case of missing request parameter, shouldn't the response status be `BAD_REQUEST`?

2024-12-10 07:29 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> +            return new ResponseEntity<>(RESPONSE_BODY_FOR_MODERATION_REQUEST_WITH_COMMIT, HttpStatus.ACCEPTED);
In case of missing request parameter, shouldn't the response status be `BAD_REQUEST`?

2024-12-10 07:29 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> +            return new ResponseEntity<>(RESPONSE_BODY_FOR_MODERATION_REQUEST_WITH_COMMIT, HttpStatus.ACCEPTED);
In case of missing request parameter, shouldn't the response status be `BAD_REQUEST`?

2024-12-10 07:29 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> +                return new ResponseEntity(RESPONSE_BODY_FOR_MODERATION_REQUEST_WITH_COMMIT, HttpStatus.ACCEPTED);
In case of missing request parameter, shouldn't the response status be `BAD_REQUEST`?

2024-12-10 07:29 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> +			return new ResponseEntity(RESPONSE_BODY_FOR_MODERATION_REQUEST_WITH_COMMIT, HttpStatus.ACCEPTED);
In case of missing request parameter, shouldn't the response status be `BAD_REQUEST`?

2024-12-10 07:29 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> +				return new ResponseEntity<>(RESPONSE_BODY_FOR_MODERATION_REQUEST, HttpStatus.ACCEPTED);
In case of missing request parameter, shouldn't the response status be `BAD_REQUEST`?

2024-12-10 07:29 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> +			return new ResponseEntity(RESPONSE_BODY_FOR_MODERATION_REQUEST_WITH_COMMIT, HttpStatus.ACCEPTED);
In case of missing request parameter, shouldn't the response status be `BAD_REQUEST`?

2024-12-10 07:29 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> +				return new ResponseEntity<>(RESPONSE_BODY_FOR_MODERATION_REQUEST, HttpStatus.ACCEPTED);
In case of missing request parameter, shouldn't the response status be `BAD_REQUEST`?

2024-12-10 07:29 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> +            @RequestParam(value = "comment", required = false) String comment
Please document the new comment parameter with `@Parameter` annotation.

2024-12-10 07:29 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> +            return new ResponseEntity(RESPONSE_BODY_FOR_MODERATION_REQUEST_WITH_COMMIT, HttpStatus.ACCEPTED);
In case of missing request parameter, shouldn't the response status be `BAD_REQUEST`?

2024-12-10 07:29 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> +            return new ResponseEntity(RESPONSE_BODY_FOR_MODERATION_REQUEST_WITH_COMMIT, HttpStatus.ACCEPTED);
In case of missing request parameter, shouldn't the response status be `BAD_REQUEST`?

2024-12-10 07:29 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> +            return new ResponseEntity(RESPONSE_BODY_FOR_MODERATION_REQUEST_WITH_COMMIT, HttpStatus.ACCEPTED);
In case of missing request parameter, shouldn't the response status be `BAD_REQUEST`?

2024-12-10 07:29 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> +            return new ResponseEntity(RESPONSE_BODY_FOR_MODERATION_REQUEST_WITH_COMMIT, HttpStatus.ACCEPTED);
In case of missing request parameter, shouldn't the response status be `BAD_REQUEST`?

2024-12-10 07:29 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> +            return new ResponseEntity(RESPONSE_BODY_FOR_MODERATION_REQUEST_WITH_COMMIT, HttpStatus.ACCEPTED);
In case of missing request parameter, shouldn't the response status be `BAD_REQUEST`?

2024-12-10 07:29 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> +            return new ResponseEntity<>(RESPONSE_BODY_FOR_MODERATION_REQUEST_WITH_COMMIT, HttpStatus.ACCEPTED);
In case of missing request parameter, shouldn't the response status be `BAD_REQUEST`?

2024-12-10 07:29 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> +			return new ResponseEntity(RESPONSE_BODY_FOR_MODERATION_REQUEST_WITH_COMMIT, HttpStatus.ACCEPTED);
In case of missing request parameter, shouldn't the response status be `BAD_REQUEST`?

2024-12-11 09:36 UTC, nikkuma7 commented
@GMishx , Addressed comment.

2024-12-11 10:09 UTC, GMishx approved these changes
Changes looks good.

2024-12-11 10:45 UTC, GMishx commented
@nikkuma7 one thing I noticed is for requests where a map object is used in request body, the additional parameter for `comment` is not used (which is technically not possible).
Can you please add the comment to the documentation of the body to add a `comment` field?

Something like
```java
@Parameter(description = "Project with `dependencyNetwork` set. Add `comment` field in the body for moderation request.",
           schema = @Schema(implementation = Project.class))
@RequestBody Map<String, Object> reqBodyMap
```

This will be required for following functions:
* `patchProjectWithNetwork()`
* `patchProject()`

2024-12-11 10:46 UTC, GMishx requested changes
Missed it.

2024-12-11 10:46 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
>      }
This function has moved to `RestControllerHelper::isWriteActionAllowed()`. Please remove from here.

2024-12-16 06:53 UTC, GMishx approved these changes
Needs test.

2024-12-16 06:53 UTC, GMishx commented
@nikkuma7 please rebase for testing.

2024-12-16 09:45 UTC, GMishx approved these changes
Changes looks good.

2025-01-06 07:21 UTC, GMishx commented
@nikkuma7 please rebase for testing.

2025-01-27 06:07 UTC, GMishx requested changes
One minor change required.

2025-01-27 06:07 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> +            @RequestParam(value = "comment", required = false) String comment
The `comment` parameter is not used here. Missed `sw360User.setCommentMadeDuringModerationRequest(comment);` ?

2025-01-31 10:08 UTC, GMishx commented
Any updates @nikkuma7 ?

2025-03-06 04:33 UTC, GMishx approved these changes

2025-03-06 04:33 UTC, merged