Prevent package's linked release getting updated when a SBOM with duplicate package is imported.
eclipse-sw360/sw360 pull request #2436
Opened 2024-04-30 09:31 UTC by akshitjoshii

closes #2428
Now when an SBOM is imported containing a duplicate pkg, the existing pkg's linked release would not be modified. 
For example : 
If this an SBOM that contains a duplicate pkg but different VCS : 
![akshitPR1](https://github.com/eclipse-sw360/sw360/assets/142988587/e71bae2a-5221-45cf-afc7-c8b3beae7a95)
 
The existing pkg : **chartjs.chartjs-color-string (0.6.0)** along with it's release is linked to the project along with the new release that is created from the SBOM. 

![2024-04-30 14_35_10-SW360_NEW  Running  - Oracle VM VirtualBox](https://github.com/eclipse-sw360/sw360/assets/142988587/29fe0c53-d28c-472f-a181-4f992e2f606d)

![2024-04-30 14_38_00-SW360_NEW  Running  - Oracle VM VirtualBox](https://github.com/eclipse-sw360/sw360/assets/142988587/091deb2c-2944-4f30-be38-948c53f48ce2)
 
With this change the projects that were using the particular pkg won't be affected and there won't be an inconsistency in them.

2024-05-03 10:31 UTC, afsahsyeda commented
@akshitjoshii How does this behave in case of Orphan packages? (No linked release in SW360, but VCS present in imported SBOM)

2024-05-03 10:32 UTC, afsahsyeda commented
@sameed20 Kindly test this PR.

2024-05-06 11:09 UTC, sameed20 commented
@akshitjoshii @afsahsyeda If an orphaned package exists in SW360, and subsequently, an attempt is made to import the same package using the CycloneDX SBOM, and if the imported SBOM contains VCS information for this package, then this orphan should be linked to the release which is being created during the import.
![pr_ak_test](https://github.com/eclipse-sw360/sw360/assets/141239852/9e59b396-b962-44ef-acad-3d98759a4c31)

Like in this example before importing an SBOM angular-mocks was an orphan package in SW360. After, importing an SBOM which contains a VCS for this package, angular-mocks package is still not getting linked to imported release.

2024-05-09 05:43 UTC, akshitjoshii commented
@sameed20 Pls test,addressed the above comments.

2024-05-09 11:22 UTC, sameed20 commented
If an SBOM contains a VCS for an orphan package in SW360, then that orphan package gets linked to the release created from the SBOM. However, if any other project was using this orphan package before the linking of this release, then this newly linked release will not appear in the License Clearing tab of that project.

@akshitjoshii is this the intended behavior ?

2024-05-10 04:16 UTC, akshitjoshii commented
Yes, this is intended as the release information was not present in the SBOM of the project and was used in the project without source information.

2024-05-10 05:50 UTC, sameed20 commented
Test Successful

2024-05-13 07:31 UTC, afsahsyeda requested changes

2024-05-13 07:31 UTC, afsahsyeda commented on backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
> +                                    if(!CommonUtils.isNotNullEmptyOrWhitespace(dupPkg.getReleaseId())){
add this on line 649 in the same If condition separated by & operator. Also use CommonUtils.isNullEmptyOrWhitespace instead.

2024-05-13 07:37 UTC, afsahsyeda requested changes

2024-05-13 07:37 UTC, afsahsyeda commented on backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
> +                                        dupPkg.setReleaseId(release.getId());
Store release.getId() and dupPkg.getReleaseId() in variables to avoid repeated function calls.

2024-05-15 06:03 UTC, afsahsyeda requested changes

2024-05-15 06:03 UTC, afsahsyeda commented on backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
> +                                    /* check if duPkg is orphan pkg or not */
This comment is not required.

2024-05-15 06:03 UTC, afsahsyeda commented on backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
> +                                    log.info("Release Id linked to orphan pkg : ",relId);
This info is redundant.

2024-05-16 07:39 UTC, sameed20 commented
Test Successful

2024-05-17 09:28 UTC, merged