feat(rest): adding additional fields in project doc.
eclipse-sw360/sw360 pull request #2438
Opened 2024-04-30 10:30 UTC by rudra-superrr

Isssue: Closes #2437

2024-08-16 06:19 UTC, GMishx requested changes
Please rebase the branch with latest main.

2024-08-16 06:19 UTC, GMishx commented on pom.xml
> +    <commons-compress.version>1.21</commons-compress.version>
Please revert the changes.

2024-08-16 06:19 UTC, GMishx commented on frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
Please remove changes from front-end.

2024-08-19 07:05 UTC, rudra-superrr commented
Note: On updating release version from UI, the newly added field release version should also get updated in projectReleaseRelationship field in project document. This functionality should be added in new UI.

2024-08-31 16:38 UTC, GMishx commented
> Note: On updating release version from UI, the newly added field release version should also get updated in projectReleaseRelationship field in project document. This functionality should be added in new UI.

Please open an issue in the https://github.com/eclipse-sw360/sw360-frontend/ project referencing this PR so it does not get missed.

Also, the test cases are failing for the PR. Please check.

2024-10-17 09:15 UTC, GMishx commented
Required data is available over `/releases` endpoint. Thus closing the PR.

2024-10-17 09:15 UTC, closed without merging