fix(rest) : Move GenerateLicenseInfoFile rest end point to SW360reportcontroller
eclipse-sw360/sw360 pull request #2442
Opened 2024-05-06 06:28 UTC by keerthi-bl

---
name: Bug report
about: Create a report to help us improve
labels: bug
---

### Description
Issue reference 
#2441 

#### How to reproduce

Sample test : 
URL : http://localhost:8080/resource/api/reports?module=licenseInfo&projectId=8fef50eafc484e33bb8ebb33618ed56d&generatorClassName=DocxGenerator&variant=DISCLOSURE

Result : 

![image](https://github.com/eclipse-sw360/sw360/assets/121924406/a863cda7-d2d3-4cb0-b2c3-d97eec3983aa)

Can download from rest!

2024-05-10 06:41 UTC, nikkuma7 commented
Test successful.

![image](https://github.com/eclipse-sw360/sw360/assets/49710817/26a4faa5-9e0b-467f-8721-8271b51c87b8)

2024-05-10 07:04 UTC, nikkuma7 commented
[LicenseInfo-6thOblication-2024-05-10_06_18_51.docx](https://github.com/eclipse-sw360/sw360/files/15271435/LicenseInfo-6thOblication-2024-05-10_06_18_51.docx)

2024-08-16 05:29 UTC, GMishx commented
@keerthi-bl please rebase with latest main to resolve merge conflict.

2024-08-31 16:43 UTC, GMishx requested changes
Build is failing. Rest looks good.

2024-08-31 16:43 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportService.java
> +import javax.servlet.http.HttpServletRequest;
```suggestion
import jakarta.servlet.http.HttpServletRequest;
```

2024-10-17 09:02 UTC, GMishx approved these changes
Changes looks good.

2024-10-17 10:34 UTC, merged