feat(rest) : Export Project Create Clearing Request
eclipse-sw360/sw360 pull request #2493
Opened 2024-06-21 08:22 UTC by keerthi-bl

### Description

Rest end point forExport Project Create Clearing Request

#### How to reproduce

Closes : #2461 

This PR should be merged after #2442

2024-07-12 08:58 UTC, nikkuma7 commented
Test successful.

![Uploading image.png…]()

2024-09-06 11:11 UTC, GMishx commented
@keerthi-bl please rebase with latest main

2024-10-17 09:32 UTC, GMishx requested changes
Please rebase with latest main

2024-10-17 09:32 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> +import javax.servlet.http.HttpServletResponse;
Please use `jakarta` not `javax`

2024-10-17 09:32 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportService.java
> +import javax.servlet.http.HttpServletRequest;
```suggestion
import jakarta.servlet.http.HttpServletRequest;
```

2024-12-10 12:43 UTC, GMishx commented
@keerthi-bl #2442 was merged. Please rebase this branch for review and test.

2024-12-13 07:48 UTC, GMishx approved these changes
Changes looks good.

2024-12-16 05:28 UTC, merged