feat(rest): endpoint to get obligations depending upon obligation level
eclipse-sw360/sw360 pull request #2611
Opened 2024-09-12 09:32 UTC by rudra-superrr

Issue: 

Description:

2024-10-01 08:19 UTC, akshitjoshii commented
Testing this PR

2024-10-08 11:30 UTC, akshitjoshii commented
Test was successful.


![image](https://github.com/user-attachments/assets/c4801834-fdef-47e3-9f9f-1cdc4a044eaf)

2024-10-17 09:58 UTC, GMishx requested changes

2024-10-17 09:58 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> +                                                             @Parameter(description = "Obligation Level")
Please provide value set of supported values as `OblLevel` is a string.

2024-10-17 09:58 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> +                                                             @RequestParam(value = "obligationLevel", required = true) String OblLevel)
```suggestion
                                                             @RequestParam(value = "obligationLevel", required = true) String oblLevel)
```

2024-10-17 09:58 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
> +                                                                            Project project, String OblLevel) throws TException {
```suggestion
                                                                            Project project, String oblLevel) throws TException {
```

2024-10-21 05:48 UTC, rudra-superrr commented
Hi @GMishx , made the changes.

2024-11-06 06:01 UTC, GMishx approved these changes
Changes looks good.

2024-11-06 06:01 UTC, merged