Fix(User): Fix XSS vulnerability for revoke token endpoint
eclipse-sw360/sw360 pull request #2751
Opened 2024-11-26 08:27 UTC by hoangnt2

Fix XSS vulnerability for revoke token endpoint

CodeQL warning: https://github.com/eclipse-sw360/sw360/security/code-scanning/87

2024-11-26 08:32 UTC, heliocastro requested changes
@hoangnt2 I started a branch deprecating commons-lang to commons-lang3.
This method you used moved to commons-text

2024-11-26 08:32 UTC, heliocastro commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/UserController.java
>  import org.apache.thrift.TException;
Change for org.apache.commons.text.StringEscapeUtils

2024-11-26 08:32 UTC, heliocastro commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/UserController.java
> +            return new ResponseEntity<>("Token not found", HttpStatus.NOT_FOUND);
Change for escapeHtml4

2024-11-26 08:40 UTC, hoangnt2 commented
> @hoangnt2 I started a branch deprecating commons-lang to commons-lang3. This method you used moved to commons-text

Escape HTML cannot resolve XSS problem, CodeQL still warns so I decided to remove **tokenName** from response. I also want to know, is there a way to run this check locally. I want to know if my fix can solve the problem before creating a PR

2024-11-26 08:51 UTC, heliocastro commented
> > @hoangnt2 I started a branch deprecating commons-lang to commons-lang3. This method you used moved to commons-text
> 
> @heliocastro Escape HTML cannot resolve XSS problem, CodeQL still warns so I decided to remove **tokenName** from response. I also want to know, is there a way to run this check locally. I want to know if my fix can solve the problem before creating a PR

Ok, for that part is fine, agreed. But remove the function unfortunately solve a small portion. We have this pervasive on the code. 
We need think in a sanitizer library

2024-11-26 09:08 UTC, hoangnt2 commented
@heliocastro OK, I will try again with escapeHtml4. Hopefully, it can solve the problem.

2024-12-23 08:43 UTC, GMishx commented
Since #2750 is merged, this PR can be updated as well.

2026-05-04 09:35 UTC, GMishx commented
GitHub marked the issue fixed in https://github.com/eclipse-sw360/sw360/commit/325cf0ef5ef38f542edd16485a4186fd22671507

Thus this PR is no longer required.

2026-05-04 09:35 UTC, closed without merging