POC for moving some configurations from properties to CouchDB
eclipse-sw360/sw360 pull request #2815
Opened 2024-12-12 02:58 UTC by hoangnt2

Note*: This PR just is a POC so only 2 properties are implemented. Other properties will be implemented if this PR is accepted

## Idea:
- Move some configuration properties from sw360.properties file to CouchDB. These properties can be changed without breaking the application
- The configuration properties related to **back-end connection** (e.g: backend.url) or **migration scripts** (e.g: enable.flexible.project.release.relationship) will not be moved to CouchDB
- The configuration properties will be stored in **sw360config** database as below
![image](https://github.com/user-attachments/assets/5de0ceca-8bc7-4a0d-b2b5-30fc1a005081)

- The configuration properties will be save and synchronize between memory (Java variable) and CouchDB to avoid query to much into CouchDB. When application is started the configuration properties will be loaded into memory and they also will be updated
when there is any update request

## New endpoints:

#### 1. Get all configuration properties (from both CouchDB and sw360.properties file)
- URL: http://localhost:8080/resource/api/configurations
- Method: GET
- Response:
```
{
    "spdx.document.enabled": "true",   // Moved properties in CouchDB
    "enable.flexible.project.release.relationship": "true" // Remaining properties in sw360.properties
}
```
#### 2. Update configuration properties in CouchDB (only moved properties are allowed to change)
- URL: http://localhost:8080/resource/api/configurations
- Method: PATCH
- Body:
```
{
    "spdx.document.enabled": "false"
}
```
- Response:
```
"Configurations are updated successfully"
```

- If configuration properties related to **back-end connection** or **migration scripts** are requested to update, return 400 error code with message:
```
"Invalid config: [${properties name} : ${value}]"
```
e.g:
```
"Invalid config: [enable.flexible.project.release.relationship : true]"
```

Please take a look at this PR and feel free to add your comment. If you have any question please let me know

2024-12-12 03:29 UTC, hoangnt2 commented
@heliocastro @GMishx, please add your comments (I haven't fixed the unit test yet so the CI fails)

2024-12-12 06:27 UTC, GMishx commented
:rocket: The idea looks great. In the same endpoint, we can list both, configs from properties file and from DB. This also allows quick update of config in running system, as current way requires restart of tomcat server to update the config constants.

Its a go ahead from me :+1:

@smrutis1 , what are your thoughts on this?

2024-12-16 09:37 UTC, smrutis1 commented
> 🚀 The idea looks great. In the same endpoint, we can list both, configs from properties file and from DB. This also allows quick update of config in running system, as current way requires restart of tomcat server to update the config constants.
> 
> Its a go ahead from me 👍
> 
> @smrutis1 , what are your thoughts on this?

The approach is great. Just an thought: As we are planning to remove `thrift` in the recent future. Would it be possible here to do it without the thrift layer.

2024-12-16 12:22 UTC, heliocastro commented
iSomething that we will need, we need to have unique ids for each entry related to to the menu itself. 
To be morfe direct, i want to restore the menu json that we construct the interface retrieved from server.
Why that ?
Well, imagine that we have a user that i restricted to access only the licenses page, or an base administrator that can only see the users and the sanitize page ?

2024-12-17 02:40 UTC, hoangnt2 commented
@heliocastro Yes, we can also retrieve the menu from the server. Do we need to allow the ADMIN user to modify the menu from the GUI? This will make the menu more flexible but could also introduce more problems.

2024-12-17 02:49 UTC, hoangnt2 commented
@smrutis1 Do we have any alternative solutions to Thrift, or should we simply remove it? Currently, I don't know how to implement this without Thrift.

2024-12-17 04:16 UTC, smrutis1 commented
> @smrutis1 Do we have any alternative solutions to Thrift, or should we simply remove it? Currently, I don't know how to implement this without Thrift.

I was planning to directly call the backend instead of passing through thrift layer. But lets take it as a separate task for analyzing it better and identify any potential pitfalls. We can proceed with this approach for now.

2025-02-28 09:28 UTC, bibhuti230185 commented
@hoangnt2 Are you still engaged on fixing this build and test fails?

2025-02-28 09:49 UTC, hoangnt2 commented
> @hoangnt2 Are you still engaged on fixing this build and test fails?
Hi @bibhuti230185, I am putting this task on hold to work on another task. I will fix this PR later.

2025-03-21 09:16 UTC, hoangnt2 commented
@GMishx, I have add some configuration that I think it can be changed from GUI.
Here are the remaining properties (I referred to your unified sw360.properties file in https://github.com/eclipse-sw360/sw360/pull/2766 (Some of them are related to Liferay and no longer used in the current back-end)
[sw360.properties.txt](https://github.com/user-attachments/files/19386091/sw360.properties.txt)

Please feel free to add your comments

2025-04-01 09:24 UTC, heliocastro commented
Sounds good.
@hoangnt2 Maybe is a good idea merge this one and gradually do the other changes ?
Otherwise will become too big

2025-04-02 02:13 UTC, hoangnt2 commented
> Sounds good. @hoangnt2 Maybe is a good idea merge this one and gradually do the other changes ? Otherwise will become too big

@heliocastro , I didn't test all the properties, so I'm worried this might cause some problems. By the way, I am also implementing the front-end for configuration changes and replacing some environment variables

2025-04-02 05:59 UTC, GMishx requested changes
Just 2 more changes to go :-)

2025-04-02 05:59 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/configuration/SW360ConfigurationsController.java
> +            description = "This method lists SW360 configurations")
Please add `tags = {"Admin"}` or `tags = {"Config"}` to the `@Operation`.

2025-04-02 05:59 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/configuration/SW360ConfigurationsController.java
> +            description = "This method lists SW360 configurations")
Please add `tags = {"Admin"}` or `tags = {"Config"}` to the `@Operation`.

2025-04-02 06:22 UTC, GMishx approved these changes
I see `@Tag` is used at controller level. Thus previous changes are no longer required.

The changes looks good. I am currently testing this PR.

2025-04-02 09:59 UTC, GMishx approved these changes
Tested, working as expected.

2025-04-02 10:00 UTC, merged