Advanced Search for project page
eclipse-sw360/sw360 pull request #2851
Opened 2024-12-23 09:37 UTC by keerthi-bl

Issue: 
Closes : #2832 

### Description
Rest end point added with following parameters for advance search in a project list page.

Version, Project responsible, State, Clearing State, additional Data.

### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?
URL : http://localhost:8080/resource/api/projects?name=update&version=1.1&state=PHASE_OUT&projectResponsible=keerthi_admin@sw360.org

Response : 
{
    <project list with above criteria should get displayed here.>
}

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

2024-12-23 09:50 UTC, GMishx requested changes
Minor changes for better documentation.

2024-12-23 09:50 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> +            @RequestParam(value = "state", required = false) String state,
Please use `ProjectState` as field type instead.

2024-12-23 09:50 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> +            @RequestParam(value = "clearingStatus", required = false) String clearingStatus,
Please use `ProjectClearingState` as field type instead.

2024-12-23 09:50 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> +                    additionalData);
Please move `group`, `projectType` and `tag` to `getFilterMap()` as well so it can be used by non-lucene search as well.

2024-12-23 09:51 UTC, GMishx commented
@keerthi-bl please fix the commit message as well.

2024-12-24 04:59 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> +            @RequestParam(value = "state", required = false) String state,
I meant to change the data type, not the field name.

2024-12-24 05:00 UTC, GMishx requested changes

2024-12-24 05:00 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> +            @RequestParam(value = "state", required = false) String ProjectState,
I meant to change the data type, not the field name.
```suggestion
            @RequestParam(value = "state", required = false) ProjectState state,
```

2024-12-24 05:00 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> +            @RequestParam(value = "clearingStatus", required = false) String ProjectClearingState,
I meant to change the data type, not the field name.
```suggestion
            @RequestParam(value = "clearingStatus", required = false) ProjectClearingState clearingStatus,
```

2025-01-03 08:26 UTC, GMishx approved these changes
Changes looks good.

2025-01-03 08:54 UTC, GMishx requested changes
Minor change needed.

During testing, discovered another issue. The function call to `getProjectsForUser()` (when lucene is `false`) gives wrong amount of projects (always 20). Will open a separate issue for the same.

2025-01-03 08:54 UTC, GMishx commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
>                  mapOfProjects, isSearchByName, sw360Projects, isNoFilter);
`getProjectResponse()` no longer requires filter of `projectType`, `group`, etc. as it is already done by `filterProjectMap()` and `refineSearch()`.

2025-01-03 09:00 UTC, GMishx commented
Created separate issue https://github.com/eclipse-sw360/sw360/issues/2854 .

Please fix the changes requested for merging this pr.

2025-01-20 09:00 UTC, keerthi-bl commented
> Created separate issue #2854 .
> 
> Please fix the changes requested for merging this pr.

@GMishx 
This issue has been fixed and pushed in the same branch here.

2025-01-27 06:16 UTC, GMishx approved these changes
Changes looks good.

2025-01-27 06:22 UTC, GMishx approved these changes
Tested, working as expected.

2025-01-27 06:22 UTC, merged